import { getLoadedChannelPlugin } from "../../channels/plugins/index.js";
import { normalizeAnyChannelId } from "../../channels/registry.js";
import type { OpenClawConfig } from "../../config/types.openclaw.js";
import { resolveOutboundChannelPlugin } from "./channel-resolution.js";

type DeliveryFormatVia = "reply" | "message_tool";

const DELIVERY_FORMAT_LEAD: Record<DeliveryFormatVia, string> = {
  reply:
    "The JSON below is generated by OpenClaw. Your visible output for this turn is delivered to this channel; follow its response_format.",
  message_tool:
    "The JSON below is generated by OpenClaw. Text you send to this channel with the message tool is rendered by it; follow its response_format.",
};

/** Renders the delivering channel's formatting contract; only delivered runs bootstrap. */
export function buildDeliveryFormatPrompt(params: {
  cfg: OpenClawConfig;
  channel?: string | null;
  accountId?: string | null;
  via?: DeliveryFormatVia;
  agentId?: string;
  allowBootstrap?: boolean;
}): string | undefined {
  if (!params.channel) {
    return undefined;
  }
  const plugin = params.allowBootstrap
    ? resolveOutboundChannelPlugin({
        channel: params.channel,
        cfg: params.cfg,
        agentId: params.agentId,
        allowBootstrap: true,
      })
    : getLoadedChannelPlugin(normalizeAnyChannelId(params.channel) ?? params.channel);
  // The plugin answers for the exact account that will render the text, so an
  // account-level capability (for example Telegram rich messages) cannot leak.
  const responseFormat = plugin?.agentPrompt?.inboundFormattingHints?.({
    cfg: params.cfg,
    accountId: params.accountId?.trim() || undefined,
  });
  if (!plugin || !responseFormat) {
    return undefined;
  }
  const payload = {
    schema: "openclaw.delivery_format.v1",
    channel: plugin.id,
    response_format: responseFormat,
  };
  return [
    "### Delivery Format",
    DELIVERY_FORMAT_LEAD[params.via ?? "reply"],
    "",
    "```json",
    JSON.stringify(payload, null, 2),
    "```",
    "",
  ].join("\n");
}

/**
 * Renders the contract for message-tool sends from a run without a reply route.
 * Callers add it only once the run's final tool surface includes `message`.
 */
export async function resolveMessageToolDeliveryFormatPrompt(params: {
  cfg: OpenClawConfig;
  agentId?: string;
  /** The message tool's current channel, when the run has one. */
  channel?: string | null;
  /** The account the message tool sends through, when the run fixes one. */
  accountId?: string | null;
}): Promise<string | undefined> {
  // Same default the message tool applies to a send without `channel`; with
  // several configured channels there is no default and no contract to pick.
  // Loaded lazily: reply turns import this module, and channel selection pulls
  // configured-plugin discovery that only background turns need.
  const channel =
    params.channel ??
    (await import("./channel-selection.runtime.js")
      .then(({ resolveMessageChannelSelection }) =>
        resolveMessageChannelSelection({ cfg: params.cfg, agentId: params.agentId }),
      )
      .then((selection) => selection.channel)
      .catch(() => undefined));
  const render = (accountId?: string | null) =>
    buildDeliveryFormatPrompt({
      cfg: params.cfg,
      channel,
      accountId,
      via: "message_tool",
      agentId: params.agentId,
      allowBootstrap: true,
    });
  if (params.accountId?.trim() || !channel) {
    return render(params.accountId);
  }
  // Without a fixed account, a send may resolve any account (for example through a
  // target binding), so only a contract every account shares is safe to give.
  const plugin = resolveOutboundChannelPlugin({
    channel,
    cfg: params.cfg,
    agentId: params.agentId,
    allowBootstrap: true,
  });
  const prompts = new Set(
    (plugin?.config.listAccountIds(params.cfg) ?? []).map((accountId) => render(accountId)),
  );
  prompts.add(render(undefined));
  return prompts.size === 1 ? [...prompts][0] : undefined;
}
