import { getLoadedChannelPlugin } from "../../channels/plugins/index.js";
import { normalizeAnyChannelId } from "../../channels/registry.js";
import type { OpenClawConfig } from "../../config/types.openclaw.js";
import { resolveOutboundChannelPlugin } from "./channel-resolution.js";

/** Renders the delivering channel's formatting contract; only delivered runs bootstrap. */
export function buildDeliveryFormatPrompt(params: {
  cfg: OpenClawConfig;
  channel?: string | null;
  accountId?: string | null;
  agentId?: string;
  allowBootstrap?: boolean;
}): string | undefined {
  if (!params.channel) {
    return undefined;
  }
  const plugin = params.allowBootstrap
    ? resolveOutboundChannelPlugin({
        channel: params.channel,
        cfg: params.cfg,
        agentId: params.agentId,
        allowBootstrap: true,
      })
    : getLoadedChannelPlugin(normalizeAnyChannelId(params.channel) ?? params.channel);
  const responseFormat = plugin?.agentPrompt?.inboundFormattingHints?.({
    cfg: params.cfg,
    accountId: params.accountId?.trim() || undefined,
  });
  if (!plugin || !responseFormat) {
    return undefined;
  }
  const payload = {
    schema: "openclaw.delivery_format.v1",
    channel: plugin.id,
    response_format: responseFormat,
  };
  return [
    "### Delivery Format",
    "The JSON below is generated by OpenClaw. Your visible output for this turn is delivered to this channel; follow its response_format.",
    "",
    "```json",
    JSON.stringify(payload, null, 2),
    "```",
    "",
  ].join("\n");
}
