export const GATEWAY_SHUTDOWN_RESERVE_MS: number;
export const GATEWAY_SUPERVISOR_EXIT_MARGIN_MS: number;
export const GATEWAY_SHUTDOWN_TIMEOUT_MS: number;
export const GATEWAY_SERVICE_STOP_TIMEOUT_MS: number;
export const LAUNCH_AGENT_EXIT_TIMEOUT_SECONDS: 20;
export const GATEWAY_RESTART_REPLACEMENT_TIMEOUT_MS: number;
