/**
 * OpenClaw-managed Chrome profile decoration.
 *
 * Applies managed-browser policy, a stable profile name, color, download
 * directory, and clean-exit markers to Chrome's profile files.
 */
import fs from "node:fs";
import path from "node:path";
import { loadJsonFile, saveJsonFile } from "openclaw/plugin-sdk/json-store";
import { asNullableRecord } from "openclaw/plugin-sdk/string-coerce-runtime";
import {
  DEFAULT_OPENCLAW_BROWSER_COLOR,
  DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME,
} from "./constants.js";

const CHROME_NETWORK_PREDICTION_DISABLED = 2;

function decoratedMarkerPath(userDataDir: string) {
  return path.join(userDataDir, ".openclaw-profile-decorated");
}

function safeReadJson(filePath: string): Record<string, unknown> | null {
  return asNullableRecord(loadJsonFile(filePath));
}

function readNestedRecord(root: unknown, key: string): Record<string, unknown> | null {
  return asNullableRecord(asNullableRecord(root)?.[key]);
}

function readDefaultProfileInfo(localState: unknown): Record<string, unknown> | null {
  return readNestedRecord(
    readNestedRecord(asNullableRecord(localState)?.profile, "info_cache"),
    "Default",
  );
}

function ensureNestedRecord(root: Record<string, unknown>, ...keys: string[]) {
  let node = root;
  for (const key of keys) {
    const child = asNullableRecord(node[key]) ?? {};
    node[key] = child;
    node = child;
  }
  return node;
}

function parseHexRgbToSignedArgbInt(hex: string): number | null {
  const cleaned = hex.trim().replace(/^#/, "");
  if (!/^[0-9a-fA-F]{6}$/.test(cleaned)) {
    return null;
  }
  const rgb = Number.parseInt(cleaned, 16);
  // Bitwise operations produce Chrome's signed 32-bit SkColor representation.
  return (0xff << 24) | rgb;
}

/** Return true when a managed Chrome profile already has desired decoration. */
export function isProfileDecorated(
  userDataDir: string,
  desiredName: string,
  desiredColorHex: string,
  desiredDownloadDir?: string,
): boolean {
  const desiredColorInt = parseHexRgbToSignedArgbInt(desiredColorHex);

  const localStatePath = path.join(userDataDir, "Local State");
  const preferencesPath = path.join(userDataDir, "Default", "Preferences");

  const localState = safeReadJson(localStatePath);
  const info = readDefaultProfileInfo(localState);

  const prefs = safeReadJson(preferencesPath);
  const browserTheme = readNestedRecord(prefs?.browser, "theme");
  const autogeneratedTheme = readNestedRecord(prefs?.autogenerated, "theme");
  const download = readNestedRecord(prefs, "download");
  const savefile = readNestedRecord(prefs, "savefile");

  const nameOk = typeof info?.name === "string" ? info.name === desiredName : true;
  const downloadOk = desiredDownloadDir
    ? download?.default_directory === desiredDownloadDir &&
      download.prompt_for_download === false &&
      download.directory_upgrade === true &&
      savefile?.default_directory === desiredDownloadDir
    : true;

  if (desiredColorInt == null) {
    // If the user provided a non-#RRGGBB value, we can only do best-effort.
    return nameOk && downloadOk;
  }

  const localSeedOk = info?.profile_color_seed === desiredColorInt;
  const prefOk =
    browserTheme?.user_color2 === desiredColorInt || autogeneratedTheme?.color === desiredColorInt;

  return nameOk && localSeedOk && prefOk && downloadOk;
}

/** Return whether this profile was initialized with Chromium's automation keychain. */
export function usesOpenClawMockKeychain(userDataDir: string): boolean {
  const localState = safeReadJson(path.join(userDataDir, "Local State"));
  return readDefaultProfileInfo(localState)?.openclaw_mock_keychain === true;
}

/** Disable Chromium network prediction in an OpenClaw-managed Chrome profile. */
export function ensureProfileNetworkPredictionDisabled(userDataDir: string) {
  const preferencesPath = path.join(userDataDir, "Default", "Preferences");
  const prefs = safeReadJson(preferencesPath) ?? {};
  // Chromium can preconnect before CDP Fetch interception. Disable that source
  // of target contact before each fresh managed-browser launch.
  ensureNestedRecord(prefs, "net").network_prediction_options = CHROME_NETWORK_PREDICTION_DISABLED;
  saveJsonFile(preferencesPath, prefs);
}

/**
 * Best-effort profile decoration (name + lobster-orange). Chrome preference keys
 * vary by version; we keep this conservative and idempotent.
 */
export function decorateOpenClawProfile(
  userDataDir: string,
  opts?: { name?: string; color?: string; downloadDir?: string; mockKeychain?: boolean },
) {
  const desiredName = opts?.name ?? DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME;
  const desiredColor = (opts?.color ?? DEFAULT_OPENCLAW_BROWSER_COLOR).toUpperCase();
  const desiredColorInt = parseHexRgbToSignedArgbInt(desiredColor);

  const localStatePath = path.join(userDataDir, "Local State");
  const preferencesPath = path.join(userDataDir, "Default", "Preferences");

  const localState = safeReadJson(localStatePath) ?? {};
  const profile = ensureNestedRecord(localState, "profile", "info_cache", "Default");
  Object.assign(profile, {
    name: desiredName,
    shortcut_name: desiredName,
    user_name: desiredName,
  });
  if (opts?.mockKeychain) {
    // Chrome preserves this key-source marker for later launches and cookie imports.
    profile.openclaw_mock_keychain = true;
  }
  Object.assign(profile, { profile_color: desiredColor, user_color: desiredColor });
  if (desiredColorInt != null) {
    Object.assign(profile, {
      profile_color_seed: desiredColorInt,
      profile_highlight_color: desiredColorInt,
      default_avatar_fill_color: desiredColorInt,
      default_avatar_stroke_color: desiredColorInt,
    });
  }
  saveJsonFile(localStatePath, localState);

  const prefs = safeReadJson(preferencesPath) ?? {};
  Object.assign(ensureNestedRecord(prefs, "profile"), {
    name: desiredName,
    profile_color: desiredColor,
    user_color: desiredColor,
  });
  if (desiredColorInt != null) {
    ensureNestedRecord(prefs, "autogenerated", "theme").color = desiredColorInt;
    ensureNestedRecord(prefs, "browser", "theme").user_color2 = desiredColorInt;
  }
  if (opts?.downloadDir) {
    Object.assign(ensureNestedRecord(prefs, "download"), {
      default_directory: opts.downloadDir,
      prompt_for_download: false,
      directory_upgrade: true,
    });
    ensureNestedRecord(prefs, "savefile").default_directory = opts.downloadDir;
  }
  saveJsonFile(preferencesPath, prefs);

  try {
    fs.writeFileSync(decoratedMarkerPath(userDataDir), `${Date.now()}\n`, "utf-8");
  } catch {
    // ignore
  }
}

/** Mark the managed Chrome profile as cleanly exited. */
export function ensureProfileCleanExit(userDataDir: string) {
  const preferencesPath = path.join(userDataDir, "Default", "Preferences");
  const prefs = safeReadJson(preferencesPath) ?? {};
  prefs.exit_type = "Normal";
  prefs.exited_cleanly = true;
  saveJsonFile(preferencesPath, prefs);
}
