/** Playwright-backed browser helpers loaded as one optional runtime object. */
import {
  closePageByTargetIdViaPlaywright,
  closePlaywrightBrowserConnection,
  createObservedDialogAbortSignalForPage,
  createPageViaPlaywright,
  ensurePageState,
  focusPageByTargetIdViaPlaywright,
  forceDisconnectPlaywrightForTarget,
  getObservedBrowserStateForPage,
  getObservedBrowserStateViaPlaywright,
  getDocumentIdentitiesViaPlaywright,
  getPageForTargetId,
  hasCachedPlaywrightBrowserConnection,
  isBrowserObservedDialogBlockedError,
  listPagesViaPlaywright,
  respondToObservedDialogOnPage,
  retirePlaywrightBrowserConnectionExact,
} from "./pw-session.js";
import {
  getConsoleMessagesViaPlaywright,
  getNetworkRequestsViaPlaywright,
  getPageErrorsViaPlaywright,
  getPageTextViaPlaywright,
} from "./pw-tools-core.activity.js";
import {
  armDialogViaPlaywright,
  armFileUploadViaPlaywright,
  downloadCurrentDocumentViaPlaywright,
  downloadViaPlaywright,
  uploadViaPlaywright,
  waitForDownloadViaPlaywright,
} from "./pw-tools-core.downloads.js";
import {
  executeActViaPlaywright,
  highlightViaPlaywright,
  screenshotWithLabelsViaPlaywright,
  setInputFilesViaPlaywright,
  takeScreenshotViaPlaywright,
} from "./pw-tools-core.interactions.js";
import { responseBodyViaPlaywright } from "./pw-tools-core.responses.js";
import {
  navigateViaPlaywright,
  pdfViaPlaywright,
  snapshotAriaViaPlaywright,
  snapshotRoleViaPlaywright,
  storeSnapshotRefsViaPlaywright,
} from "./pw-tools-core.snapshot.js";
import {
  emulateMediaViaPlaywright,
  setDeviceViaPlaywright,
  setExtraHTTPHeadersViaPlaywright,
  setGeolocationViaPlaywright,
  setHttpCredentialsViaPlaywright,
  setLocaleViaPlaywright,
  setOfflineViaPlaywright,
  setTimezoneViaPlaywright,
} from "./pw-tools-core.state.js";
import {
  cookiesClearViaPlaywright,
  cookiesGetViaPlaywright,
  cookiesSetManyViaPlaywright,
  cookiesSetViaPlaywright,
  storageClearViaPlaywright,
  storageGetViaPlaywright,
  storageSetViaPlaywright,
} from "./pw-tools-core.storage.js";
import { traceStartViaPlaywright, traceStopViaPlaywright } from "./pw-tools-core.trace.js";

export const pwAi = {
  downloadCurrentDocumentViaPlaywright,
  closePageByTargetIdViaPlaywright,
  closePlaywrightBrowserConnection,
  retirePlaywrightBrowserConnectionExact,
  createPageViaPlaywright,
  ensurePageState,
  forceDisconnectPlaywrightForTarget,
  focusPageByTargetIdViaPlaywright,
  createObservedDialogAbortSignalForPage,
  getObservedBrowserStateForPage,
  getObservedBrowserStateViaPlaywright,
  getDocumentIdentitiesViaPlaywright,
  getPageForTargetId,
  hasCachedPlaywrightBrowserConnection,
  isBrowserObservedDialogBlockedError,
  listPagesViaPlaywright,
  respondToObservedDialogOnPage,
  armDialogViaPlaywright,
  armFileUploadViaPlaywright,
  cookiesClearViaPlaywright,
  cookiesGetViaPlaywright,
  cookiesSetManyViaPlaywright,
  cookiesSetViaPlaywright,
  downloadViaPlaywright,
  emulateMediaViaPlaywright,
  executeActViaPlaywright,
  getConsoleMessagesViaPlaywright,
  getNetworkRequestsViaPlaywright,
  getPageErrorsViaPlaywright,
  getPageTextViaPlaywright,
  highlightViaPlaywright,
  navigateViaPlaywright,
  pdfViaPlaywright,
  responseBodyViaPlaywright,
  setDeviceViaPlaywright,
  setExtraHTTPHeadersViaPlaywright,
  setGeolocationViaPlaywright,
  setHttpCredentialsViaPlaywright,
  setInputFilesViaPlaywright,
  setLocaleViaPlaywright,
  setOfflineViaPlaywright,
  setTimezoneViaPlaywright,
  snapshotAriaViaPlaywright,
  snapshotRoleViaPlaywright,
  storeSnapshotRefsViaPlaywright,
  screenshotWithLabelsViaPlaywright,
  storageClearViaPlaywright,
  storageGetViaPlaywright,
  storageSetViaPlaywright,
  takeScreenshotViaPlaywright,
  traceStartViaPlaywright,
  traceStopViaPlaywright,
  uploadViaPlaywright,
  waitForDownloadViaPlaywright,
};
