// Auto-generated by scripts/generate-bundled-channel-config-metadata.ts. Do not edit directly.

type BundledChannelIdMetadata = {
  channelId: string;
  aliases?: readonly string[];
  order?: number;
  configurable?: boolean;
  label?: string;
};

export const GENERATED_BUNDLED_CHANNEL_IDS: readonly BundledChannelIdMetadata[] = [
  {
    channelId: "a2a",
    order: 75,
    label: "A2A",
  },
  {
    channelId: "buzz",
    order: 56,
    label: "Buzz",
  },
  {
    channelId: "clickclack",
    order: 85,
    label: "ClickClack",
  },
  {
    channelId: "discord",
    label: "Discord",
  },
  {
    channelId: "feishu",
    aliases: ["lark"],
    order: 35,
    label: "Feishu",
  },
  {
    channelId: "googlechat",
    aliases: ["gchat", "google-chat"],
    order: 55,
    label: "Google Chat",
  },
  {
    channelId: "imessage",
    aliases: ["imsg"],
    label: "iMessage",
  },
  {
    channelId: "irc",
    aliases: ["internet-relay-chat"],
    label: "IRC",
  },
  {
    channelId: "line",
    order: 75,
    label: "LINE",
  },
  {
    channelId: "matrix",
    order: 70,
    label: "Matrix",
  },
  {
    channelId: "mattermost",
    order: 65,
    label: "Mattermost",
  },
  {
    channelId: "msteams",
    aliases: ["teams"],
    order: 60,
    label: "Microsoft Teams",
  },
  {
    channelId: "nextcloud-talk",
    aliases: ["nc", "nc-talk"],
    order: 65,
    label: "Nextcloud Talk",
  },
  {
    channelId: "nostr",
    order: 55,
    label: "Nostr",
  },
  {
    channelId: "qa-channel",
    order: 999,
    configurable: false,
    label: "QA Channel",
  },
  {
    channelId: "raft",
    order: 72,
    label: "Raft",
  },
  {
    channelId: "reef",
    label: "Reef",
  },
  {
    channelId: "signal",
    label: "Signal",
  },
  {
    channelId: "slack",
    label: "Slack",
  },
  {
    channelId: "sms",
    order: 88,
    label: "SMS",
  },
  {
    channelId: "synology-chat",
    order: 90,
    label: "Synology Chat",
  },
  {
    channelId: "telegram",
    label: "Telegram",
  },
  {
    channelId: "tlon",
    order: 90,
    label: "Tlon",
  },
  {
    channelId: "twitch",
    aliases: ["twitch-chat"],
    label: "Twitch",
  },
  {
    channelId: "whatsapp",
    label: "WhatsApp",
  },
  {
    channelId: "zalo",
    aliases: ["zl"],
    order: 80,
    label: "Zalo",
  },
  {
    channelId: "zalouser",
    aliases: ["zlu"],
    order: 85,
    label: "Zalo Personal",
  },
];
