import { GATEWAY_RESTART_REPLACEMENT_TIMEOUT_MS } from "../../infra/gateway-shutdown-budget.js";

export const DEFAULT_RESTART_HEALTH_TIMEOUT_MS = GATEWAY_RESTART_REPLACEMENT_TIMEOUT_MS;

export const DEFAULT_RESTART_HEALTH_DELAY_MS = 500;
export const DEFAULT_RESTART_HEALTH_ATTEMPTS = Math.ceil(
  DEFAULT_RESTART_HEALTH_TIMEOUT_MS / DEFAULT_RESTART_HEALTH_DELAY_MS,
);

export const INTERRUPTED_UPDATE_SETTLE_PROBES = Math.ceil(DEFAULT_RESTART_HEALTH_ATTEMPTS / 10);
// Preserve the former aggregate: health settling, HTTP readiness, and two inspections.
export const INTERRUPTED_UPDATE_SETTLE_TIMEOUT_MS =
  Math.floor(DEFAULT_RESTART_HEALTH_TIMEOUT_MS / 4) +
  (INTERRUPTED_UPDATE_SETTLE_PROBES - 1) * DEFAULT_RESTART_HEALTH_DELAY_MS +
  3 * 10_000;
