import type { WhatsAppQaScenarioImplementation } from "./whatsapp-live.contracts.js";
import {
  whatsappQaGroupAudioGatingScenario,
  whatsappQaGroupOutboundAudioScenario,
  whatsappQaGroupOutboundMediaScenario,
  whatsappQaGroupOutboundPollScenario,
  whatsappQaInboundStructuredMessagesScenario,
  whatsappQaMessageActionsScenario,
  whatsappQaOutboundDocumentPreservesFilenameScenario,
  whatsappQaOutboundPollScenario,
  whatsappQaOutboundSendSerializationScenario,
} from "./whatsapp-live.scenario-implementations.capabilities.js";
import {
  whatsappQaBroadcastGroupFanoutScenario,
  whatsappQaCanaryScenario,
  whatsappQaGroupActivationAlwaysScenario,
  whatsappQaGroupPendingHistoryContextScenario,
  whatsappQaGroupReplyToBotTriggersScenario,
  whatsappQaGroupReplyToMessageScenario,
  whatsappQaMentionGatingScenario,
  whatsappQaReplyToMessageScenario,
  whatsappQaReplyToModeBatchedScenario,
  whatsappQaTopLevelReplyShapeScenario,
} from "./whatsapp-live.scenario-implementations.conversation.js";
import {
  whatsappQaApprovalExecDenyNativeScenario,
  whatsappQaApprovalExecGroupReactionNativeScenario,
  whatsappQaApprovalExecNativeScenario,
  whatsappQaApprovalExecReactionNativeScenario,
  whatsappQaApprovalPluginNativeScenario,
  whatsappQaGroupAllowlistBlockScenario,
  whatsappQaReplyDeliveryShapeScenario,
  whatsappQaStatusReactionLifecycleScenario,
  whatsappQaStatusReactionsScenario,
  whatsappQaStreamFinalMessageAccountingScenario,
} from "./whatsapp-live.scenario-implementations.delivery.js";
import {
  whatsappQaAgentMessageActionReactScenario,
  whatsappQaAgentMessageActionUploadFileScenario,
  whatsappQaAudioPreflightScenario,
  whatsappQaGroupAgentMessageActionReactScenario,
  whatsappQaGroupAgentMessageActionUploadFileScenario,
  whatsappQaInboundImageCaptionScenario,
  whatsappQaInboundReactionNoTriggerScenario,
  whatsappQaOutboundMediaMatrixScenario,
  whatsappQaReplyContextIsolationScenario,
} from "./whatsapp-live.scenario-implementations.user-path.js";

export const whatsappScenarioImplementations: Record<string, WhatsAppQaScenarioImplementation> = {
  whatsappQaGroupAudioGatingScenario,
  whatsappQaGroupOutboundAudioScenario,
  whatsappQaGroupOutboundMediaScenario,
  whatsappQaGroupOutboundPollScenario,
  whatsappQaInboundStructuredMessagesScenario,
  whatsappQaMessageActionsScenario,
  whatsappQaOutboundDocumentPreservesFilenameScenario,
  whatsappQaOutboundPollScenario,
  whatsappQaOutboundSendSerializationScenario,
  whatsappQaBroadcastGroupFanoutScenario,
  whatsappQaCanaryScenario,
  whatsappQaGroupActivationAlwaysScenario,
  whatsappQaGroupPendingHistoryContextScenario,
  whatsappQaGroupReplyToBotTriggersScenario,
  whatsappQaGroupReplyToMessageScenario,
  whatsappQaMentionGatingScenario,
  whatsappQaReplyToMessageScenario,
  whatsappQaReplyToModeBatchedScenario,
  whatsappQaTopLevelReplyShapeScenario,
  whatsappQaApprovalExecDenyNativeScenario,
  whatsappQaApprovalExecGroupReactionNativeScenario,
  whatsappQaApprovalExecNativeScenario,
  whatsappQaApprovalExecReactionNativeScenario,
  whatsappQaApprovalPluginNativeScenario,
  whatsappQaGroupAllowlistBlockScenario,
  whatsappQaReplyDeliveryShapeScenario,
  whatsappQaStatusReactionLifecycleScenario,
  whatsappQaStatusReactionsScenario,
  whatsappQaStreamFinalMessageAccountingScenario,
  whatsappQaAgentMessageActionReactScenario,
  whatsappQaAgentMessageActionUploadFileScenario,
  whatsappQaAudioPreflightScenario,
  whatsappQaGroupAgentMessageActionReactScenario,
  whatsappQaGroupAgentMessageActionUploadFileScenario,
  whatsappQaInboundImageCaptionScenario,
  whatsappQaInboundReactionNoTriggerScenario,
  whatsappQaOutboundMediaMatrixScenario,
  whatsappQaReplyContextIsolationScenario,
};
