/** LaunchAgent plist, environment-file, and atomic publication ownership. */
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { isDeepStrictEqual } from "node:util";
import { normalizeEnvVarKey } from "../infra/host-env-security.js";
import { resolveGatewayServiceDescription } from "./constants.js";
import { resolveLaunchAgentLabel } from "./launchd-label.js";
import {
  LAUNCH_AGENT_ENV_WRAPPER_SHELL,
  buildLaunchAgentPlist,
  normalizeLaunchdPlistXml,
  quoteLaunchAgentEnvironmentValue,
  readLaunchAgentProgramArgumentsFromFile,
} from "./launchd-plist.js";
import { assertNoSystemLaunchDaemonOwnership } from "./launchd-system.js";
import { formatLine, normalizeWindowsPathSeparators } from "./output.js";
import { resolveDaemonHomeDir, resolveGatewayStateDir } from "./paths.js";
import { resolveGatewaySupervisorLogPaths } from "./restart-logs.js";
import { preserveServicePolicyXml } from "./service-policy-xml.js";
import {
  publishServiceFile,
  readServiceFileState,
  type GatewayServiceDefinitionTransactionHooks,
} from "./service-stage.js";
import type { GatewayServiceEnv, GatewayServiceInstallArgs } from "./service-types.js";
import {
  assertGatewayServiceUpdateCurrent,
  withGatewayServiceInstallationRecovery,
} from "./service-update-authority.js";

const LAUNCH_AGENT_DIR_MODE = 0o755;
// launchd rejects user LaunchAgent plists without group/other read access on
// current macOS. Secrets stay in the separate 0600 environment file.
const LAUNCH_AGENT_PLIST_MODE = 0o644;
const LAUNCH_AGENT_PRIVATE_DIR_MODE = 0o700;
const LAUNCH_AGENT_ENV_FILE_MODE = 0o600;
const LAUNCH_AGENT_ENV_WRAPPER_MODE = 0o700;
const LAUNCH_AGENT_ENV_DIR_NAME = "service-env";
const LAUNCH_AGENT_ENV_FILE_HEADER =
  "# Generated by OpenClaw. Do not edit while the gateway service is installed.";
export function resolveLaunchAgentPlistPathForLabel(
  env: Record<string, string | undefined>,
  label: string,
): string {
  const home = normalizeWindowsPathSeparators(resolveDaemonHomeDir(env));
  return path.posix.join(home, "Library", "LaunchAgents", `${label}.plist`);
}

function resolveLaunchAgentEnvDir(env: GatewayServiceEnv): string {
  return path.join(resolveGatewayStateDir(env), LAUNCH_AGENT_ENV_DIR_NAME);
}

export function resolveLaunchAgentEnvFilePath(env: GatewayServiceEnv, label: string): string {
  return path.join(resolveLaunchAgentEnvDir(env), `${label}.env`);
}

export function resolveLaunchAgentEnvWrapperPath(env: GatewayServiceEnv, label: string): string {
  return path.join(resolveLaunchAgentEnvDir(env), `${label}-env-wrapper.sh`);
}

function collectLaunchAgentEnvironmentEntries(
  environment: GatewayServiceEnv | undefined,
): Array<[string, string]> {
  const entries: Array<[string, string]> = [];
  for (const [rawKey, rawValue] of Object.entries(environment ?? {})) {
    const key = normalizeEnvVarKey(rawKey, { portable: true });
    const value = rawValue?.trim();
    // Empty NODE_OPTIONS intentionally clears launchd's inherited Node flags.
    if (!key || value === undefined || (!value && key !== "NODE_OPTIONS")) {
      continue;
    }
    entries.push([key, value]);
  }
  return entries.toSorted(([left], [right]) => left.localeCompare(right));
}

function buildLaunchAgentEnvironmentFile(entries: Array<[string, string]>): string {
  return [
    LAUNCH_AGENT_ENV_FILE_HEADER,
    ...entries.map(([key, value]) => `export ${key}=${quoteLaunchAgentEnvironmentValue(value)}`),
    "",
  ].join("\n");
}

export function buildLaunchAgentEnvironmentWrapper(): string {
  return `#!/bin/sh
set -eu
invalid_env() {
  echo "Invalid LaunchAgent environment file; run openclaw gateway install --force to repair the service." >&2
  exit 78
}
[ "$#" -ge 2 ] || invalid_env
env_file="$1"
shift
[ -f "$env_file" ] && [ -r "$env_file" ] || invalid_env
IFS= read -r env_header < "$env_file" || invalid_env
[ "$env_header" = '${LAUNCH_AGENT_ENV_FILE_HEADER}' ] || invalid_env
. "$env_file"
exec "$@"
`;
}

// Published installations used this wrapper; recognize its exact bytes so an
// update can replace it without treating installer output as operator behavior.
export function isGeneratedLaunchAgentEnvironmentWrapper(contents: string): boolean {
  return (
    contents === buildLaunchAgentEnvironmentWrapper() ||
    contents ===
      `#!/bin/sh
set -eu
env_file="$1"
shift
if [ -f "$env_file" ]; then
  . "$env_file"
fi
exec "$@"
`
  );
}

async function resolveLaunchAgentEnvironmentWrapperOverwriteWarnings(params: {
  wrapperPath: string;
}): Promise<string[]> {
  const existingWrapper = await fs.readFile(params.wrapperPath, "utf8").catch(() => null);
  if (existingWrapper === null || isGeneratedLaunchAgentEnvironmentWrapper(existingWrapper)) {
    return [];
  }
  return [
    `Existing generated LaunchAgent env wrapper at ${params.wrapperPath} contains custom behavior and will be overwritten; move custom behavior to openclaw gateway install --wrapper <path> or OPENCLAW_WRAPPER.`,
  ];
}

function writeLaunchAgentOverwriteWarnings(
  stdout: NodeJS.WritableStream | undefined,
  warn: ((message: string) => void) | undefined,
  warnings: readonly string[],
): void {
  for (const warning of warnings) {
    if (warn) {
      warn(warning);
      continue;
    }
    if (!stdout) {
      continue;
    }
    stdout.write(`${formatLine("Warning", warning)}\n`);
  }
}

function isLaunchAgentEnvironmentWrapperArgs(params: {
  programArguments: string[];
  envFilePath: string;
  wrapperPath: string;
}): boolean {
  return (
    (params.programArguments[0] === params.wrapperPath &&
      params.programArguments[1] === params.envFilePath) ||
    (params.programArguments[0] === LAUNCH_AGENT_ENV_WRAPPER_SHELL &&
      params.programArguments[1] === params.wrapperPath &&
      params.programArguments[2] === params.envFilePath)
  );
}

async function prepareLaunchAgentProgramArguments(params: {
  env: GatewayServiceEnv;
  label: string;
  programArguments: string[];
  environment: GatewayServiceEnv | undefined;
  stdout?: NodeJS.WritableStream;
  warn?: (message: string) => void;
  definitionTransaction: GatewayServiceDefinitionTransactionHooks;
}): Promise<{
  programArguments: string[];
  inlineEnvironment?: GatewayServiceEnv;
}> {
  const entries = collectLaunchAgentEnvironmentEntries(params.environment);
  if (entries.length === 0) {
    return { programArguments: params.programArguments };
  }

  // Environment values with secrets live in an owner-only env file instead of
  // inline plist XML, which can be harder to rotate and audit.
  const envDir = resolveLaunchAgentEnvDir(params.env);
  const envFilePath = resolveLaunchAgentEnvFilePath(params.env, params.label);
  const wrapperPath = resolveLaunchAgentEnvWrapperPath(params.env, params.label);
  const generatedWrapper = buildLaunchAgentEnvironmentWrapper();
  await ensureSecureDirectory(envDir, LAUNCH_AGENT_PRIVATE_DIR_MODE);
  await publishServiceFile({
    filePath: envFilePath,
    contents: buildLaunchAgentEnvironmentFile(entries),
    mode: LAUNCH_AGENT_ENV_FILE_MODE,
    definitionTransaction: params.definitionTransaction,
  });
  const overwriteWarnings = await resolveLaunchAgentEnvironmentWrapperOverwriteWarnings({
    wrapperPath,
  });
  writeLaunchAgentOverwriteWarnings(params.stdout, params.warn, overwriteWarnings);
  await publishServiceFile({
    filePath: wrapperPath,
    contents: generatedWrapper,
    mode: LAUNCH_AGENT_ENV_WRAPPER_MODE,
    definitionTransaction: params.definitionTransaction,
  });

  if (
    isLaunchAgentEnvironmentWrapperArgs({
      programArguments: params.programArguments,
      envFilePath,
      wrapperPath,
    })
  ) {
    return { programArguments: params.programArguments };
  }

  return {
    programArguments: [
      LAUNCH_AGENT_ENV_WRAPPER_SHELL,
      wrapperPath,
      envFilePath,
      ...params.programArguments,
    ],
  };
}

export function resolveLaunchAgentPlistPath(env: GatewayServiceEnv): string {
  const label = resolveLaunchAgentLabel(env);
  return resolveLaunchAgentPlistPathForLabel(env, label);
}

export function resolveLaunchAgentEnvironmentReadOptions(env: GatewayServiceEnv, label: string) {
  return {
    expectedEnvironmentWrapperPath: resolveLaunchAgentEnvWrapperPath(env, label),
    expectedEnvironmentFilePath: resolveLaunchAgentEnvFilePath(env, label),
    generatedEnvironmentLabel: label,
  };
}

async function ensureLaunchAgentPlistReadable(plistPath: string): Promise<void> {
  assertGatewayServiceUpdateCurrent();
  await fs.chmod(plistPath, LAUNCH_AGENT_PLIST_MODE).catch(() => undefined);
}

type LaunchAgentFileSnapshot = { contents: Buffer; mode: number };

export async function readExistingLaunchAgentPlist(
  plistPath: string,
): Promise<LaunchAgentFileSnapshot | null> {
  try {
    const handle = await fs.open(plistPath, "r");
    try {
      const contents = await handle.readFile();
      const metadata = await handle.stat();
      return { contents, mode: metadata.mode & 0o7777 };
    } finally {
      await handle.close();
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return null;
    }
    throw error;
  }
}

type LaunchAgentFileState = NonNullable<Awaited<ReturnType<typeof readServiceFileState>>>;
type LaunchAgentFilePublication = Awaited<ReturnType<typeof captureLaunchAgentFiles>>;

/** Captured file identities bound rollback to this install's actual publications. */
async function captureLaunchAgentFiles(paths: string[]) {
  const originals = new Map<
    string,
    { snapshot: LaunchAgentFileSnapshot | null; state: LaunchAgentFileState | null }
  >();
  await withGatewayServiceInstallationRecovery(
    async () => {
      for (const file of paths) {
        const state = await readServiceFileState(file);
        const snapshot = await readExistingLaunchAgentPlist(file);
        const contents = snapshot?.contents ?? null;
        if (
          !isDeepStrictEqual(state, await readServiceFileState(file)) ||
          (state === null) !== (contents === null) ||
          (state &&
            contents &&
            createHash("sha256").update(contents).digest("hex") !== state.sha256)
        ) {
          throw new Error("LaunchAgent artifact changed while capturing its original definition.");
        }
        originals.set(file, { snapshot, state });
      }
    },
    async () => false,
  );
  const published = new Map<string, LaunchAgentFileState>();
  const prepared = new Map<string, LaunchAgentFileState>();
  const matchesPublication = (
    current: LaunchAgentFileState | null,
    expected: LaunchAgentFileState,
  ): current is LaunchAgentFileState =>
    current !== null &&
    (["dev", "ino", "sha256", "mode", "size", "mtimeMs"] as const).every(
      (key) => current[key] === expected[key],
    );
  const verify = async (file: string) => {
    const current = await readServiceFileState(file);
    const expected = published.get(file);
    if (
      expected
        ? !matchesPublication(current, expected)
        : !isDeepStrictEqual(current, originals.get(file)?.state)
    ) {
      throw new Error(`LaunchAgent artifact changed after capture or publication: ${file}`);
    }
    return current;
  };
  const beforeWrite = async () => {
    assertGatewayServiceUpdateCurrent();
    // A rename may finish before publication confirmation or directory fsync fails.
    for (const [file, pending] of prepared) {
      const current = await readServiceFileState(file);
      if (matchesPublication(current, pending)) {
        published.set(file, current);
      } else {
        await verify(file);
      }
      prepared.delete(file);
    }
    for (const file of originals.keys()) {
      await verify(file);
    }
    assertGatewayServiceUpdateCurrent();
  };
  const refuseTaskPublication = async () => {
    throw new Error("LaunchAgent file receipts cannot publish Scheduled Tasks.");
  };
  const hooks: GatewayServiceDefinitionTransactionHooks = {
    assertCurrent: assertGatewayServiceUpdateCurrent,
    beforeWrite,
    filePrepared: async (file, temporary) => {
      if (!originals.has(file) || temporary === null) {
        throw new Error("Not a captured LaunchAgent publication target.");
      }
      const pending = await readServiceFileState(temporary);
      assertGatewayServiceUpdateCurrent();
      if (!pending) {
        throw new Error("Prepared LaunchAgent artifact disappeared before publication.");
      }
      prepared.set(file, pending);
    },
    fileWritten: async (file, contents) => {
      const current = await readServiceFileState(file);
      const pending = prepared.get(file);
      assertGatewayServiceUpdateCurrent();
      if (
        !pending ||
        !matchesPublication(current, pending) ||
        contents === null ||
        current?.sha256 !== createHash("sha256").update(contents).digest("hex")
      ) {
        throw new Error(`LaunchAgent artifact changed after publication: ${file}`);
      }
      published.set(file, current);
      prepared.delete(file);
    },
    taskPrepared: refuseTaskPublication,
    taskWritten: refuseTaskPublication,
  };
  return {
    originals,
    hooks,
    assertCurrent: beforeWrite,
    restore: async (): Promise<boolean> => {
      if (!published.size && !prepared.size) {
        return false;
      }
      await beforeWrite();
      if (!published.size) {
        return false;
      }
      const order = (file: string) =>
        file === paths[0] ? 1 : originals.get(file)!.snapshot ? 0 : 2;
      // Restore original inputs, then their reference, before retiring newly created inputs.
      for (const file of [...published.keys()].toSorted((a, b) => order(a) - order(b))) {
        const original = originals.get(file)!;
        if (original.snapshot !== null && original.state) {
          await publishServiceFile({
            filePath: file,
            contents: original.snapshot.contents,
            mode: original.snapshot.mode,
            definitionTransaction: hooks,
          });
          original.state = published.get(file)!;
        } else {
          await verify(file);
          assertGatewayServiceUpdateCurrent();
          await fs.unlink(file);
          original.state = null;
        }
        published.delete(file);
      }
      return true;
    },
  };
}

export function captureLaunchAgentInstallFiles(env: GatewayServiceEnv) {
  const label = resolveLaunchAgentLabel(env);
  return captureLaunchAgentFiles([
    resolveLaunchAgentPlistPath(env),
    resolveLaunchAgentEnvFilePath(env, label),
    resolveLaunchAgentEnvWrapperPath(env, label),
  ]);
}

async function publishLaunchAgentPlist(params: {
  label: string;
  plistPath: string;
  contents: string;
  definitionTransaction: GatewayServiceDefinitionTransactionHooks;
}): Promise<void> {
  await publishServiceFile({
    filePath: params.plistPath,
    contents: params.contents,
    mode: LAUNCH_AGENT_PLIST_MODE,
    definitionTransaction: params.definitionTransaction,
    beforeRename: () => assertNoSystemLaunchDaemonOwnership(params.label),
  });
  await assertNoSystemLaunchDaemonOwnership(params.label);
}

async function ensureSecureDirectory(
  targetPath: string,
  dirMode = LAUNCH_AGENT_DIR_MODE,
): Promise<void> {
  assertGatewayServiceUpdateCurrent();
  await fs.mkdir(targetPath, { recursive: true, mode: dirMode });
  try {
    const stat = await fs.stat(targetPath);
    const mode = stat.mode & 0o777;
    const forbiddenMode = dirMode === LAUNCH_AGENT_PRIVATE_DIR_MODE ? 0o077 : 0o022;
    const tightenedMode = mode & ~forbiddenMode;
    if (tightenedMode !== mode) {
      assertGatewayServiceUpdateCurrent();
      await fs.chmod(targetPath, tightenedMode);
    }
  } catch {
    // Best effort: keep install working even if chmod/stat is unavailable.
  }
}

async function ensureLaunchAgentEnvironmentDirectories(
  environment: Record<string, string | undefined> | undefined,
): Promise<void> {
  const tmpDir = environment?.TMPDIR?.trim();
  if (tmpDir) {
    await ensureSecureDirectory(tmpDir, LAUNCH_AGENT_PRIVATE_DIR_MODE);
  }
}

export async function writeLaunchAgentPlist(
  args: GatewayServiceInstallArgs,
  publication?: LaunchAgentFilePublication,
): Promise<{ plistPath: string; stdoutPath: string }> {
  assertGatewayServiceUpdateCurrent();
  const definitionTransaction = args.definitionTransaction ?? publication?.hooks;
  if (!definitionTransaction) {
    const captured = await captureLaunchAgentInstallFiles(args.env);
    return withGatewayServiceInstallationRecovery(
      () => writeLaunchAgentPlist(args, captured),
      captured.restore,
    );
  }
  const { env, programArguments, workingDirectory, environment, description, stdout, warn } = args;
  const label = resolveLaunchAgentLabel(env);
  await assertNoSystemLaunchDaemonOwnership(label);

  const { logDir, stdoutPath } = resolveGatewaySupervisorLogPaths(env, { platform: "darwin" });
  await ensureSecureDirectory(logDir);

  const plistPath = resolveLaunchAgentPlistPathForLabel(env, label);
  const home = normalizeWindowsPathSeparators(resolveDaemonHomeDir(env));
  const libraryDir = path.posix.join(home, "Library");
  await ensureSecureDirectory(home);
  await ensureSecureDirectory(libraryDir);
  await ensureSecureDirectory(path.dirname(plistPath));
  await ensureLaunchAgentEnvironmentDirectories(environment);
  const prepared = await prepareLaunchAgentProgramArguments({
    env,
    label,
    programArguments,
    environment,
    stdout,
    warn,
    definitionTransaction,
  });

  const serviceDescription = resolveGatewayServiceDescription({ env, description });
  let plist = buildLaunchAgentPlist({
    label,
    comment: serviceDescription,
    programArguments: prepared.programArguments,
    workingDirectory,
    stdoutPath,
    // Both handles target one file: launchd cannot merge streams, and darwin
    // diagnostics reads only stdout (readLastGatewayErrorLine).
    stderrPath: stdoutPath,
    environment: prepared.inlineEnvironment,
  });
  if (definitionTransaction.preservePolicy?.length) {
    plist = preserveServicePolicyXml(
      plist,
      await normalizeLaunchdPlistXml(await fs.readFile(plistPath)),
      definitionTransaction.preservePolicy,
      "plist",
    );
  }
  await publishLaunchAgentPlist({ label, plistPath, contents: plist, definitionTransaction });
  return { plistPath, stdoutPath };
}
export async function rewriteLaunchAgentPlistForRestart({
  env,
  label,
  plistPath,
  stdout,
  warn,
}: {
  env: GatewayServiceEnv;
  label: string;
  plistPath: string;
  stdout?: NodeJS.WritableStream;
  warn?: (message: string) => void;
}): Promise<boolean> {
  const existing = await readLaunchAgentProgramArgumentsFromFile(
    plistPath,
    resolveLaunchAgentEnvironmentReadOptions(env, label),
  );
  if (!existing?.programArguments.length) {
    return false;
  }

  const publication = await captureLaunchAgentInstallFiles(env);
  const definitionTransaction = publication.hooks;
  return withGatewayServiceInstallationRecovery(async () => {
    const { logDir, stdoutPath } = resolveGatewaySupervisorLogPaths(env, { platform: "darwin" });
    await ensureSecureDirectory(logDir);

    const serviceDescription = resolveGatewayServiceDescription({
      env,
    });
    // Restart rewrites must retire install provenance from legacy plists instead
    // of copying it into the next canonical definition.
    const canonicalEnvironment = {
      ...existing.environment,
      OPENCLAW_SERVICE_VERSION: undefined,
    };
    const prepared = await prepareLaunchAgentProgramArguments({
      env,
      label,
      programArguments: existing.programArguments,
      environment: canonicalEnvironment,
      stdout,
      warn,
      definitionTransaction,
    });
    const plist = buildLaunchAgentPlist({
      label,
      comment: serviceDescription,
      programArguments: prepared.programArguments,
      workingDirectory: existing.workingDirectory,
      stdoutPath,
      // Both handles target one file: launchd cannot merge streams, and darwin
      // diagnostics reads only stdout (readLastGatewayErrorLine).
      stderrPath: stdoutPath,
      environment: prepared.inlineEnvironment,
    });
    const previousPlist = await fs.readFile(plistPath, "utf8").catch(() => "");
    if (previousPlist === plist) {
      await ensureLaunchAgentPlistReadable(plistPath);
      return false;
    }
    await publishLaunchAgentPlist({ label, plistPath, contents: plist, definitionTransaction });
    return true;
  }, publication.restore);
}
