import type { nothing, TemplateResult } from "lit";
import type { ImageLightboxItem } from "../../components/image-lightbox.types.ts";
import type { ChatAttachment, HumanMention } from "../../lib/chat/chat-types.ts";
import type { SessionToolOverrides } from "../../lib/sessions/patch.ts";
import type { ChatAttachmentReadLifecycle } from "../chat/components/chat-attachment-reads.ts";
import type { HumanMentionDirectory } from "../chat/components/chat-composer-mention-menu.ts";
import type { CapabilityMenuProps } from "../chat/components/chat-composer-types.ts";
import type { SidebarContent } from "../chat/components/chat-sidebar-content-types.ts";
import type { NewSessionComposerTextareaController } from "./composer-controller.ts";
import type { NewSessionVisibility } from "./create-params.ts";

export type NewSessionComposerOptions = {
  renderCritters: (floorEnabled: boolean) => TemplateResult | typeof nothing;
  attachmentLimits?: { maxBytes: number; maxImageBytes: number };
  attachmentReads?: ChatAttachmentReadLifecycle;
  attachments: ChatAttachment[];
  canSubmit: boolean;
  getAttachments: () => ChatAttachment[];
  message: string;
  mentions?: readonly HumanMention[];
  getMentions?: () => readonly HumanMention[];
  mentionDirectory?: HumanMentionDirectory;
  modelControl?: TemplateResult | typeof nothing;
  permissionControl?: TemplateResult | typeof nothing;
  pendingAttachmentReads: number;
  readSignal: AbortSignal;
  requiresModifier: boolean;
  requestUpdate: () => void;
  refreshCommands?: () => void | Promise<void>;
  submitDisabledReason?: string;
  blockedSubmitNotice?: string;
  dictationActive?: boolean;
  dictationPreview?: string;
  dictationStatus?: TemplateResult | typeof nothing;
  nativeTerminal?: boolean;
  onUnsupportedAttachment?: () => void;
  submitting: boolean;
  textareaController: NewSessionComposerTextareaController;
  voiceControl?: TemplateResult | typeof nothing;
  messageLocked?: boolean;
  visibility?: NewSessionVisibility;
  draftAvailable?: boolean;
  capabilityMenu?: CapabilityMenuProps;
  toolOverrides?: SessionToolOverrides | null;
  onAttachmentsChange: (attachments: ChatAttachment[]) => void;
  onPendingReadsChange: (delta: 1 | -1) => void;
  onInput: (message: string, mentions?: readonly HumanMention[]) => void;
  onOpenImage?: (item: ImageLightboxItem) => void;
  onOpenSidebar?: (content: SidebarContent) => void;
  onVisibilityChange?: (visibility: NewSessionVisibility) => void;
  onSubmit: () => void;
  onBackgroundSubmit?: () => void;
};
