/** OpenClaw-owned agent runtime facade; the plugin SDK module owns the adapter. */
export {
  Agent,
  bashExecutionToText,
  buildSessionContext,
  calculateContextTokens,
  collectEntriesForBranchSummaryFromBranches,
  compact,
  estimateContextTokens,
  estimateTokens,
  generateBranchSummary,
  generateSummary,
  openClawAgentCoreRuntime,
  prepareCompaction,
  shouldCompact,
  BRANCH_SUMMARY_PREFIX,
  BRANCH_SUMMARY_SUFFIX,
  COMPACTION_SUMMARY_PREFIX,
  COMPACTION_SUMMARY_SUFFIX,
  IMAGE_BLOCK_TOKENS,
} from "../../plugin-sdk/agent-core.js";
export type {
  AfterToolCallContext,
  AfterToolCallResult,
  AgentEvent,
  AgentMessage,
  AgentOptions,
  AgentState,
  AgentTool,
  AgentToolResult,
  AgentToolUpdateCallback,
  BashExecutionMessage,
  CompactionPreparation,
  CompactionResult,
  CompactionSummaryPrompt,
  SessionTreeEntry,
  StreamFn,
  ThinkingLevel,
  ToolExecutionMode,
} from "../../plugin-sdk/agent-core.js";
