import { BUILTIN_THEMES } from "../../../packages/gateway-protocol/src/theme.js";

export const defaultControlUiFeatureMethods = [
  "chat.abort",
  "chat.metadata",
  "chat.startup",
  "config.apply",
  "config.patch",
  "config.schema",
  "config.set",
  "device.scopes.requestUpgrade",
  "device.scopes.waitUpgrade",
  "session.members.add",
  "session.members.list",
  "session.members.listEvidence",
  "session.members.remove",
  "session.visibility.set",
  "sessions.abort",
  "sessions.patchMany",
  "sessions.branches.switch",
  "sessions.compact",
  "sessions.create",
  "sessions.delete",
  "sessions.dispatch",
  "sessions.fork",
  "sessions.groups.delete",
  "sessions.groups.defaults",
  "sessions.groups.list",
  "sessions.groups.put",
  "sessions.groups.rename",
  "sessions.groups.update",
  "sessions.patch",
  "sessions.reclaim",
  "sessions.reset",
  "sessions.rewind",
  "sessions.search",
  "users.github.status",
  "users.github.authorize.start",
  "users.github.authorize.poll",
  "users.github.authorize.cancel",
  "users.github.disconnect",
  "sessions.github.options",
  "sessions.github.status",
  "sessions.github.confirm",
  "themes.list",
  "themes.get",
  "themes.set",
  "themes.import",
  "tools.github.status",
  "tools.github.configure",
  "tools.github.authorize.start",
  "tools.github.authorize.poll",
  "tools.github.authorize.cancel",
  "update.hold",
  "update.run",
  "update.runs.get",
  "update.runs.list",
  "update.status",
  "worktrees.branches",
] as const;

export function createControlUiThemeResponses() {
  const selection = {
    theme: BUILTIN_THEMES[0],
    current: { id: "claw", mode: "system", scope: "gateway", overrides: {} },
  };
  return {
    "themes.list": { ...selection, themes: BUILTIN_THEMES },
    "themes.get": selection,
  };
}
