// Shared target sets for config help copy quality tests.

export const ROOT_SECTIONS = [
  "meta",
  "env",
  "wizard",
  "diagnostics",
  "logging",
  "update",
  "browser",
  "ui",
  "tui",
  "auth",
  "models",
  "nodeHost",
  "agents",
  "tools",
  "bindings",
  "broadcast",
  "attachments",
  "messages",
  "commands",
  "approvals",
  "session",
  "cron",
  "transcripts",
  "hooks",
  "channels",
  "surfaces",
  "discovery",
  "talk",
  "gateway",
  "cloudWorkers",
  "memory",
  "plugins",
] as const;

export const ENUM_EXPECTATIONS: Record<string, string[]> = {
  "session.groupScope": ['"main"', '"per-group"'],
  "bindings[].session.groupScope": ['"main"', '"per-group"'],
  "skills.workshop.autonomous.mode": ['"off"', '"propose"', '"auto"'],
  "memory.citations": ['"auto"', '"on"', '"off"'],
  "models.mode": ['"merge"', '"replace"'],
  "models.providers.*.auth": ['"api-key"', '"token"', '"oauth"', '"aws-sdk"'],
  "gateway.reload.mode": ['"off"', '"hybrid"'],
  "nodeHost.workerRuns.isolation": ['"none"', '"container"'],
  "approvals.exec.mode": ['"session"', '"targets"', '"both"'],
  "bindings[].match.peer.kind": ['"direct"', '"group"', '"channel"', '"dm"'],
  "broadcast.strategy": ['"parallel"', '"sequential"'],
  "hooks.mappings[].action": ['"wake"', '"agent"'],
  "hooks.mappings[].wakeMode": ['"now"', '"next-heartbeat"'],
  "hooks.gmail.tailscale.mode": ['"off"', '"serve"', '"funnel"'],
  "hooks.gmail.thinking": ['"off"', '"minimal"', '"low"', '"medium"', '"high"'],
  "messages.queue.mode": ['"steer"', '"followup"', '"collect"', '"interrupt"'],
  "messages.queue.drop": ['"old"', '"new"', '"summarize"'],
  "channels.defaults.groupPolicy": ['"open"', '"disabled"', '"allowlist"'],
  "channels.defaults.contextVisibility": ['"all"', '"allowlist"', '"allowlist_quote"'],
  "gateway.mode": ['"local"', '"remote"'],
  "gateway.bind": ['"auto"', '"lan"', '"loopback"', '"custom"', '"tailnet"'],
  "gateway.auth.mode": ['"none"', '"token"', '"password"', '"trusted-proxy"'],
  "gateway.tailscale.mode": ['"off"', '"serve"', '"funnel"'],
  "browser.profiles.*.driver": ['"openclaw"', '"clawd"', '"existing-session"', '"extension"'],
  "discovery.mdns.mode": ['"off"', '"minimal"', '"full"'],
  "diagnostics.otel.protocol": ['"http/protobuf"'],
  "diagnostics.otel.logsExporter": ['"otlp"', '"stdout"', '"both"'],
  "logging.level": ['"silent"', '"fatal"', '"error"', '"warn"', '"info"', '"debug"', '"trace"'],
  "logging.consoleLevel": [
    '"silent"',
    '"fatal"',
    '"error"',
    '"warn"',
    '"info"',
    '"debug"',
    '"trace"',
  ],
  "logging.consoleStyle": ['"pretty"', '"json"'],
  "update.channel": ['"stable"', '"extended-stable"', '"beta"', '"dev"'],
  "agents.defaults.contextInjection": ['"always"', '"continuation-skip"', '"never"'],
  "agents.defaults.compaction.mode": ['"default"', '"safeguard"'],
  "agents.defaults.compaction.thinkingLevel": [
    '"off"',
    '"minimal"',
    '"low"',
    '"medium"',
    '"high"',
    '"xhigh"',
    '"adaptive"',
    '"max"',
    '"ultra"',
    '"inherit"',
  ],
  "agents.defaults.compaction.identifierPolicy": ['"strict"', '"off"'],
};
