export const AGENT_MODEL_FIELD_LABELS: Record<string, string> = {
  "agents.defaults.models": "Models",
  "agents.defaults.modelSelectionScope": "Model Selection Scope",
  "agents.defaults.modelPolicy": "Model Policy",
  "agents.defaults.modelPolicy.allow": "Allowed Models",
  "agents.defaults.models.*.agentRuntime": "Default Agent Model Runtime",
  "agents.defaults.models.*.agentRuntime.id": "Default Agent Model Runtime ID",
  "agents.defaults.models.*.codeMode": "Code Mode",
  "agents.defaults.model.primary": "Primary Model",
  "agents.defaults.model.fallbacks": "Model Fallbacks",
  "agents.defaults.embeddedAgent.cyberFailover": "Cyber Policy Failover",
  "agents.defaults.embeddedAgent.cyberFailover.mode": "Cyber Policy Failover Mode",
  "agents.defaults.embeddedAgent.cyberFailover.model": "Cyber Policy Failover Model",
  "agents.defaults.embeddedAgent.cyberFailover.cooloffMs": "Cyber Policy Failover Cooloff",
  "agents.defaults.utilityModel": "Utility Model",
  "agents.entries.*.utilityModel": "Agent Utility Model",
  "agents.defaults.decisionModel": "Decision Model",
  "agents.defaults.experimental.decisionAssistance": "Decision Assistance (Experimental)",
  "agents.entries.*.decisionModel": "Agent Decision Model",
  "agents.defaults.imageModel.primary": "Image Model",
  "agents.defaults.imageModel.fallbacks": "Image Model Fallbacks",
  "agents.defaults.mediaModels.image.primary": "Image Generation Model",
  "agents.defaults.mediaModels.image.fallbacks": "Image Generation Model Fallbacks",
  "agents.defaults.mediaModels.image.timeoutMs": "Image Generation Timeout (ms)",
  "agents.defaults.mediaModels.video.primary": "Video Generation Model",
  "agents.defaults.mediaModels.video.fallbacks": "Video Generation Model Fallbacks",
  "agents.defaults.mediaModels.video.timeoutMs": "Video Generation Timeout (ms)",
  "agents.defaults.mediaModels.music.primary": "Music Generation Model",
  "agents.defaults.mediaModels.music.fallbacks": "Music Generation Model Fallbacks",
  "agents.defaults.voiceModel.primary": "Voice Model",
  "agents.defaults.voiceModel.fallbacks": "Voice Model Fallbacks",
  "agents.defaults.voiceModel.timeoutMs": "Voice Timeout (ms)",
  "agents.defaults.pdfModel.primary": "PDF Model",
  "agents.defaults.pdfModel.fallbacks": "PDF Model Fallbacks",
  "agents.defaults.pdfMaxMb": "PDF Max Size (MB)",
  "agents.defaults.pdfMaxPages": "PDF Max Pages",
  "agents.defaults.imageMaxDimensionPx": "Image Max Dimension (px)",
  "agents.defaults.imageQuality": "Image Quality",
};
