// Defines the Gateway config labels exposed by schema metadata.
export const GATEWAY_FIELD_LABELS: Record<string, string> = {
  gateway: "Gateway",
  "gateway.port": "Gateway Port",
  "gateway.mode": "Gateway Mode",
  "gateway.bind": "Gateway Bind Mode",
  "gateway.customBindHost": "Gateway Custom Bind Host",
  "gateway.portals": "Gateway Portals",
  "gateway.portals.ingress": "Private Portal Ingress",
  "gateway.portals.ingress.domain": "Portal Wildcard Domain",
  "gateway.portals.ingress.port": "Portal Ingress Loopback Port",
  "gateway.publicOrigin": "Gateway Public Origin",
  "gateway.controlUi": "Control UI",
  "gateway.controlUi.enabled": "Control UI Enabled",
  "gateway.cliAgents": "CLI Agents",
  "gateway.cliAgents.enabled": "CLI Agents Enabled",
  "gateway.terminal": "Operator Terminal",
  "gateway.terminal.enabled": "Operator Terminal Enabled",
  "gateway.terminal.shell": "Operator Terminal Shell",
  "gateway.terminal.detachedSessionTimeoutSeconds": "Operator Terminal Detached Session Timeout",
  "gateway.auth": "Gateway Auth",
  "gateway.auth.mode": "Gateway Auth Mode",
  "gateway.auth.allowTailscale": "Gateway Auth Allow Tailscale Identity",
  "gateway.auth.identityScopes": "Gateway Identity Scope Grants",
  "gateway.auth.rateLimit": "Gateway Auth Rate Limit",
  "gateway.auth.trustedProxy": "Gateway Trusted Proxy Auth",
  "gateway.auth.trustedProxy.cloudflareAccessOidc": "Cloudflare Access OIDC GitHub Identity",
  "gateway.auth.trustedProxy.cloudflareAccessOidc.issuer": "Cloudflare Access Issuer",
  "gateway.auth.trustedProxy.cloudflareAccessOidc.providerId": "Cloudflare Access OIDC Provider ID",
  "gateway.auth.trustedProxy.cloudflareAccessOidc.githubAccountIdClaim": "GitHub Account ID Claim",
  "gateway.auth.trustedProxy.deviceAutoApprove": "Trusted Proxy Device Auto-Approval",
  "gateway.auth.trustedProxy.deviceAutoApprove.enabled":
    "Trusted Proxy Device Auto-Approval Enabled",
  "gateway.auth.trustedProxy.deviceAutoApprove.scopes": "Trusted Proxy Device Auto-Approval Scopes",
  "gateway.roles": "Gateway Operator Roles",
  "gateway.roles.default": "Default Operator Role",
  "gateway.roles.definitions": "Operator Role Definitions",
  "gateway.roles.definitions.*": "Operator Role Definition",
  "gateway.roles.definitions.*.sessions": "Operator Role Session Access",
  "gateway.roles.definitions.*.sessions.others": "Operator Role Access to Other Sessions",
  "gateway.roles.definitions.*.sandbox": "Operator Role Sandbox Isolation",
  "gateway.roles.definitions.*.agents": "Operator Role Allowed Agents",
  "gateway.roles.definitions.*.scopes": "Operator Role Scope Ceiling",
  "gateway.roles.definitions.*.accessPolicyPlugin": "Operator Role Access Policy Plugin",
  "gateway.trustedProxies": "Gateway Trusted Proxy CIDRs",
  "gateway.allowRealIpFallback": "Gateway Allow x-real-ip Fallback",
  "gateway.tools": "Gateway Tool Exposure Policy",
  "gateway.tools.allow": "Gateway Tool Allowlist",
  "gateway.tools.deny": "Gateway Tool Denylist",
  "gateway.tailscale": "Gateway Tailscale",
  "gateway.tailscale.mode": "Gateway Tailscale Mode",
  "gateway.tailscale.preserveFunnel": "Gateway Tailscale External Funnel Migration Guard",
  "gateway.remote": "Remote Gateway",
  "gateway.remote.transport": "Remote Gateway Transport",
  "gateway.reload": "Config Reload",
  "gateway.tls": "Gateway TLS",
  "gateway.tls.enabled": "Gateway TLS Enabled",
  "gateway.tls.autoGenerate": "Gateway TLS Auto-Generate Cert",
  "gateway.tls.certPath": "Gateway TLS Certificate Path",
  "gateway.tls.keyPath": "Gateway TLS Key Path",
  "gateway.tls.caPath": "Gateway TLS CA Path",
  "gateway.http": "Gateway HTTP API",
  "gateway.http.endpoints": "Gateway HTTP Endpoints",
  "gateway.http.securityHeaders": "Gateway HTTP Security Headers",
  "gateway.http.securityHeaders.strictTransportSecurity": "Strict Transport Security Header",
  "gateway.remote.url": "Remote Gateway URL",
  "gateway.remote.sshTarget": "Remote Gateway SSH Target",
  "gateway.remote.sshIdentity": "Remote Gateway SSH Identity",
  "gateway.remote.sshHostKeyPolicy": "Remote Gateway SSH Host-Key Policy",
  "gateway.remote.token": "Remote Gateway Token",
  "gateway.remote.password": "Remote Gateway Password",
  "gateway.remote.edgeAuth": "Remote Gateway Edge Auth Headers",
  "gateway.remote.tlsFingerprint": "Remote Gateway TLS Fingerprint",
  "gateway.auth.token": "Gateway Token",
  "gateway.auth.password": "Gateway Password",
};
