// Approval forwarding and reviewer field labels.
export const APPROVAL_FIELD_LABELS: Record<string, string> = {
  approvals: "Approvals",
  "approvals.exec": "Exec Approval Forwarding",
  "approvals.exec.enabled": "Forward Exec Approvals",
  "approvals.exec.mode": "Approval Forwarding Mode",
  "approvals.exec.agentFilter": "Approval Agent Filter",
  "approvals.exec.sessionFilter": "Approval Session Filter",
  "approvals.exec.targets": "Approval Forwarding Targets",
  "approvals.exec.targets[].channel": "Approval Target Channel",
  "approvals.exec.targets[].to": "Approval Target Destination",
  "approvals.exec.targets[].accountId": "Approval Target Account ID",
  "approvals.exec.targets[].threadId": "Approval Target Thread ID",
  "approvals.plugin": "Plugin Approval Forwarding",
  "approvals.plugin.enabled": "Forward Plugin Approvals",
  "approvals.plugin.mode": "Plugin Approval Forwarding Mode",
  "approvals.plugin.agentFilter": "Plugin Approval Agent Filter",
  "approvals.plugin.sessionFilter": "Plugin Approval Session Filter",
  "approvals.plugin.targets": "Plugin Approval Forwarding Targets",
  "approvals.plugin.targets[].channel": "Plugin Approval Target Channel",
  "approvals.plugin.targets[].to": "Plugin Approval Target Destination",
  "approvals.plugin.targets[].accountId": "Plugin Approval Target Account ID",
  "approvals.plugin.targets[].threadId": "Plugin Approval Target Thread ID",
  "approvals.plugin.slack": "Slack Plugin Reviewers",
  "approvals.plugin.slack.approvers": "Default Slack Plugin Reviewers",
  "approvals.plugin.slack.plugins": "Slack Plugin Reviewer Overrides",
};
