export const SESSION_FIELD_LABELS: Record<string, string> = {
  session: "Session",
  "session.scope": "Session Scope",
  "session.dmScope": "DM Session Scope",
  "session.groupScope": "Group Session Scope",
  "session.notifyOnCreate": "Notify Home on Session Creation",
  "session.identityLinks": "Session Identity Links",
  "session.resetTriggers": "Session Reset Triggers",
  "session.reset": "Session Reset Policy",
  "session.reset.mode": "Session Reset Mode",
  "session.reset.atHour": "Session Daily Reset Hour",
  "session.reset.idleMinutes": "Session Reset Idle Minutes",
  "session.resetByType": "Session Reset by Chat Type",
  "session.resetByType.direct": "Session Reset (Direct)",
  "session.resetByType.group": "Session Reset (Group)",
  "session.resetByType.thread": "Session Reset (Thread)",
  "session.resetByChannel": "Session Reset by Channel",
  "session.store": "Session Store Path",
  "session.mainKey": "Session Main Key",
  "session.sendPolicy": "Session Send Policy",
  "session.sendPolicy.default": "Session Send Policy Default Action",
  "session.sendPolicy.rules": "Session Send Policy Rules",
  "session.sendPolicy.rules[].action": "Session Send Rule Action",
  "session.sendPolicy.rules[].match": "Session Send Rule Match",
  "session.sendPolicy.rules[].match.channel": "Session Send Rule Channel",
  "session.sendPolicy.rules[].match.chatType": "Session Send Rule Chat Type",
  "session.sendPolicy.rules[].match.keyPrefix": "Session Send Rule Key Prefix",
  "session.sendPolicy.rules[].match.rawKeyPrefix": "Session Send Rule Raw Key Prefix",
  "session.threadBindings": "Session Thread Bindings",
  "session.threadBindings.enabled": "Thread Binding Enabled",
  "session.threadBindings.idleHours": "Thread Binding Idle Timeout (hours)",
  "session.threadBindings.maxAgeHours": "Thread Binding Max Age (hours)",
  "session.threadBindings.spawnSessions": "Thread-Bound Session Spawns",
  "session.threadBindings.defaultSpawnContext": "Thread Spawn Context",
  "session.sharing": "Session Sharing Modes",
  "session.sharing.readOnly": "Allow Read-only Sessions",
  "session.sharing.suggest": "Allow Suggest Sessions",
  "session.sharing.drafts": "Allow Draft Sessions",
  "session.maintenance": "Session Maintenance",
  "session.maintenance.coldStorage": "Transcript Cold Storage",
  "session.maintenance.coldStorage.enabled": "Automatically Archive Old Transcripts",
  "session.maintenance.coldStorage.afterDays": "Archive After Inactive Days",
  "session.maintenance.mode": "Session Maintenance Mode",
  "session.maintenance.pruneAfter": "Session Prune After",
  "session.maintenance.archiveDashboardAfter": "Archive Inactive Dashboard Sessions After",
  "session.maintenance.maxEntries": "Session Max Entries",
  "session.maintenance.preserveRecent": "Preserve Recent Sessions",
  "session.maintenance.resetArchiveRetention": "Session Reset Archive Retention",
  "session.maintenance.maxDiskBytes": "Session Max Disk Budget",
  "session.maintenance.highWaterBytes": "Session Disk High-water Target",
};
