import type { ConfigFileSnapshot } from "../../config/types.openclaw.js";
import type { PackageUpdateTransaction } from "../../infra/package-update-steps.js";
import type { UpdateStateSchemaVersion } from "../../infra/update-candidate-state.js";
import type { UpdateChannel } from "../../infra/update-channels.js";
import type { readControlPlaneUpdateSentinelMeta } from "../../infra/update-control-plane-sentinel.js";
import type { loadInstalledPluginIndexInstallRecords } from "../../plugins/installed-plugin-index-records.js";
import type { OpenClawSchemaVersions } from "../../state/openclaw-schema-versions.js";
import type { UpdateCommandOptions } from "./shared.js";
import type { UpdateRestartParams } from "./update-command-service-context-types.js";
import type { UpdateServiceLoadBoundary } from "./update-command-service-load.js";
export type FinishUpdateParams = UpdateRestartParams & {
  coreAlreadyCurrent?: boolean;
  serviceLoadBoundary?: UpdateServiceLoadBoundary;
  failure?: { cause: unknown; detail: string };
  mutationStarted: boolean;
  expectedVersion?: string;
  previousInstallRoot?: string;
  installKindChanged: boolean;
  configSnapshot: ConfigFileSnapshot;
  requestedChannel: UpdateChannel | null;
  storedChannel: UpdateChannel | null;
  channel: UpdateChannel;
  downgradeRisk: boolean;
  opts: UpdateCommandOptions;
  controlPlaneUpdateSentinelMeta: Awaited<ReturnType<typeof readControlPlaneUpdateSentinelMeta>>;
  preUpdatePluginInstallRecords: Awaited<ReturnType<typeof loadInstalledPluginIndexInstallRecords>>;
  startedAt: number;
  packageUpdateNodeRunner?: string;
  packageTransaction?: PackageUpdateTransaction;
  schemaVersions?: UpdateStateSchemaVersion[];
  candidateSchemaVersions?: OpenClawSchemaVersions;
  previousSchemaVersions?: OpenClawSchemaVersions;
  previousVerified?: boolean;
  activationConfig?: import("./update-command-config-snapshot.js").UpdateConfigSnapshot;
  rollbackBlockedReason?: "state-migrated-no-rollback" | "rollback-state-unverified";
};
