import type { UiState } from "./ui-types.js";

export function stateFingerprint(state: UiState): string {
  const msgs = state.snapshot?.messages;
  const ev = state.snapshot?.events;
  return JSON.stringify({
    mc: msgs?.length ?? 0,
    lm: msgs?.at(-1)?.id ?? null,
    cc: state.snapshot?.conversations.length ?? 0,
    tc: state.snapshot?.threads.length ?? 0,
    ec: ev?.length ?? 0,
    lc: ev?.at(-1)?.cursor ?? -1,
    cu: state.bootstrap?.controlUiUrl ?? null,
    rs: state.bootstrap?.runner.status,
    ra: state.bootstrap?.runner.startedAt,
    rf: state.bootstrap?.runner.finishedAt,
    re: state.bootstrap?.runner.error,
    rpo: state.runnerPlanOverride
      ? `${state.runnerPlanOverride.status}:${state.runnerPlanOverride.selectedScenarios.length}:${state.runnerPlanOverride.exclusions.length}:${state.runnerPlanOverride.errors.join("|")}`
      : null,
    ss: state.scenarioRun?.status,
    sc: state.scenarioRun?.counts,
    so: state.scenarioRun?.scenarios.map((o) => o.status).join(","),
    rp: state.latestReport?.generatedAt,
    cs: state.bootstrap?.runnerCatalog.status,
    cl: state.bootstrap?.runnerCatalog.real.length ?? 0,
    cps: state.captureSessions.length,
    cse: state.captureSessions[0]?.eventCount ?? 0,
    cei: state.selectedCaptureSessionIds.join(","),
    cec: state.captureEvents.length,
    ceh: state.captureEvents[0]?.host ?? null,
    ccp: state.captureQueryPreset,
    ccq: state.captureQueryRows.length,
    ccv: state.captureCoverage?.totalEvents ?? 0,
    ccpv: state.captureCoverage?.providers[0]?.value ?? null,
    ccss: state.captureStartupStatus?.proxy.ok ?? null,
    ccsg: state.captureStartupStatus?.gateway.ok ?? null,
    ccce: state.captureControlsExpanded,
    ccse: state.captureSummaryExpanded,
    ccsx: state.captureSelectedSessionsExpanded,
    ccsv: state.captureSavedViews.map((view) => `${view.id}:${view.name}`).join("|"),
    scc: state.sidebarCollapsed,
    scp: state.sidebarPanel,
    cck: state.captureKindFilter.join(","),
    ccpf: state.captureProviderFilter.join(","),
    cchf: state.captureHostFilter.join(","),
    cchm: state.captureHeaderMode,
    ccgm: state.captureGroupMode,
    cctl: state.captureTimelineLaneMode,
    ccts: state.captureTimelineLaneSort,
    cctps: state.captureTimelinePreviousLaneSort,
    cctq: state.captureTimelineLaneSearch,
    cctz: state.captureTimelineZoom,
    cctsm: state.captureTimelineSparklineMode,
    cctws: state.captureTimelineWindowStartPct,
    cctwe: state.captureTimelineWindowEndPct,
    cctba: state.captureTimelineBrushAnchorPct,
    cctbc: state.captureTimelineBrushCurrentPct,
    cctff: state.captureTimelineFocusSelectedFlow,
    cctfm: state.captureTimelineFocusedLaneMode,
    cctft: state.captureTimelineFocusedLaneThreshold,
    ccdp: state.captureDetailPlacement,
    ccds: state.captureDetailSplitPct,
    ccdsd: state.captureDetailSplitDragging,
    ccdv: state.captureDetailView,
    ccpdv: state.capturePreferredDetailView,
    ccdfl: state.captureFlowDetailLayout,
    ccdpl: state.capturePayloadDetailLayout,
    ccdpe: state.capturePayloadExtent,
    ccpes: state.capturePayloadEventSort,
    ccpef: state.capturePayloadEventFilter,
    ccli: state.captureCollapsedLaneIds.join(","),
    ccpi: state.capturePinnedLaneIds.join(","),
    er: state.error,
    el: state.evidenceLoading,
    ee: state.evidenceError,
    ep: state.evidence?.evidencePath ?? null,
    eg: state.evidence?.generatedAt ?? null,
    ecnt: state.evidence?.entries.length ?? 0,
    eac: state.evidence?.entries.reduce((sum, entry) => sum + entry.artifacts.length, 0) ?? 0,
    epr: state.evidence?.producerContext?.rootPath ?? null,
    esf: state.evidenceStatusFilter,
    eaf: state.evidenceArtifactFilter,
    esq: state.evidenceSearchText,
    ese: state.selectedEvidenceEntryKey,
  });
}
