import { syncIosVersioning } from "./lib/ios-version.ts";
import { parseVersionSyncArgs } from "./lib/version-script-args.ts";

export function parseArgs(argv: string[]) {
  return parseVersionSyncArgs(argv, { allowAppStoreRevision: true });
}

function printUsage(): void {
  process.stdout.write(
    "Usage: node --import tsx scripts/ios-sync-versioning.ts [--write|--check] [--version YYYY.M.D] [--revision 0-9] [--root dir]\n\nValidates that iOS versioning inputs can produce generated local artifacts.\n",
  );
}

function main(argv = process.argv.slice(2)): number {
  const options = parseArgs(argv);
  if (options.help) {
    printUsage();
    return 0;
  }

  syncIosVersioning({
    appStoreRevision: options.appStoreRevision,
    mode: options.mode,
    releaseVersion: options.releaseVersion,
    rootDir: options.rootDir,
  });

  if (options.mode === "check") {
    process.stdout.write("iOS versioning inputs are valid.\n");
  } else {
    process.stdout.write(
      "iOS versioning inputs are valid; local artifacts are generated by iOS prep commands.\n",
    );
  }
  return 0;
}

try {
  process.exitCode = main();
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
}
