export const gatewayPluginTestFiles: string[];
export const gatewayDatabaseWorkerTestFiles: string[];
export const gatewayCoreTestInclude: string[];
export const gatewayCoreTestExclude: string[];
export const gatewayClientTestInclude: string[];
export const gatewayClientTestExclude: string[];
export const gatewayMethodsIsolatedTestFiles: string[];
export const gatewayMethodsTestInclude: string[];
export const gatewayMethodsTestExclude: string[];
export const gatewayServerBackedHttpTestFiles: string[];
export const gatewayServerExcludedTestFiles: string[];
export const gatewayServerIsolatedTestFiles: string[];
export const gatewayServerSerialTestFiles: string[];
export function isGatewayServerBackedHttpTestFile(file: string): boolean;
export function isGatewayServerTestFile(file: string): boolean;
