// Lightweight in-memory queue for human-readable system events that should be
// prefixed to the next prompt. We intentionally avoid persistence to keep
// events ephemeral. Events are session-scoped and require an explicit key.

import {
  normalizeOptionalLowercaseString,
  normalizeOptionalString,
} from "@openclaw/normalization-core/string-coerce";
import { createSubsystemLogger } from "../logging/subsystem.js";
import { channelRouteDedupeKey } from "../plugin-sdk/channel-route.js";
import { parseAgentSessionKey } from "../routing/session-key.js";
import { resolveGlobalMap } from "../shared/global-singleton.js";
import {
  mergeDeliveryContext,
  normalizeDeliveryContext,
} from "../utils/delivery-context.shared.js";
import type { DeliveryContext } from "../utils/delivery-context.types.js";
import {
  execRequestMatches,
  readExecRequestOwners,
  withExecRequestOwners,
  type ExecRequestIdentity,
} from "./exec-request-context.js";
import { generateSecureUuid } from "./secure-random.js";
import {
  getSystemEventStorePath,
  isSystemEventStoreCurrent,
  registerSystemEventStoreOwner,
  recordSystemEventStoreReplaced,
} from "./system-event-ownership.js";

export type SystemEvent = {
  /**
   * OpenClaw-assigned opaque identity for one queued occurrence. Preserve it when returning a
   * snapshot to consume. It changes on replacement or re-enqueue; optional only for legacy
   * ID-less compatibility.
   */
  id?: string;
  text: string;
  ts: number;
  contextKey?: string | null;
  deliveryContext?: DeliveryContext;
  /** An unresolved exec attempt must not be regenerated by an unrelated model turn. */
  deliveryHeld?: boolean;
  /** Queued by work a conversation turn started, not heartbeat or automation work. */
  fromConversationTurn?: true;
  sessionStorePath?: string | null;
};

const MAX_EVENTS = 20;
const log = createSubsystemLogger("system-events");

export class SystemEventQueueFullError extends Error {
  constructor() {
    super(
      `System event queue is full (${MAX_EVENTS} pending). Let the session process pending events before retrying the notification.`,
    );
    this.name = "SystemEventQueueFullError";
  }
}

type SessionQueue = {
  queue: SystemEvent[];
  lastContextKey: string | null;
};

const SYSTEM_EVENT_QUEUES_KEY = Symbol.for("openclaw.systemEvents.queues");

const queues = resolveGlobalMap<string, SessionQueue>(SYSTEM_EVENT_QUEUES_KEY, "close-only");
registerSystemEventStoreOwner(SYSTEM_EVENT_QUEUES_KEY, () => {
  for (const [key, entry] of queues) {
    const retained = entry.queue.filter((event) =>
      isSystemEventStoreCurrent(key, event.sessionStorePath),
    );
    if (retained.length === entry.queue.length) {
      continue;
    }
    entry.queue = retained;
    resetQueueState(key, entry);
    recordSystemEventStoreReplaced();
  }
});

type SystemEventOptions = {
  sessionKey: string;
  sessionStorePath?: string | null;
  contextKey?: string | null;
  deliveryContext?: DeliveryContext;
  fromConversationTurn?: boolean;
  /** Replace the pending event for this context and delivery route. Requires contextKey. */
  replace?: boolean;
};

type ReceiptOptions = { allowDuplicate?: boolean };

function requireSessionKey(key?: string | null): string {
  const trimmed = normalizeOptionalString(key) ?? "";
  const parsed = parseAgentSessionKey(trimmed);
  if (!parsed) {
    throw new Error("system events require an agent-qualified sessionKey");
  }
  return `agent:${parsed.agentId}:${parsed.rest}`;
}

function normalizeContextKey(key?: string | null): string | null {
  return normalizeOptionalLowercaseString(key) ?? null;
}

function getSessionQueue(sessionKey: string): SessionQueue | undefined {
  const key = requireSessionKey(sessionKey);
  const entry = queues.get(key);
  if (entry) {
    const live = entry.queue.filter(
      (event) => !readExecRequestOwners(event)?.some((owner) => owner.signal.aborted),
    );
    if (live.length !== entry.queue.length) {
      entry.queue = live;
      resetQueueState(key, entry);
    }
  }
  return queues.get(key);
}

function getOrCreateSessionQueue(key: string): SessionQueue {
  const existing = getSessionQueue(key);
  if (existing) {
    return existing;
  }
  const created: SessionQueue = {
    queue: [],
    lastContextKey: null,
  };
  queues.set(key, created);
  return created;
}

function cloneSystemEvent(event: SystemEvent): SystemEvent {
  return {
    ...event,
    ...(event.deliveryContext ? { deliveryContext: { ...event.deliveryContext } } : {}),
  };
}

export function isSystemEventContextChanged(
  sessionKey: string,
  contextKey?: string | null,
): boolean {
  const existing = getSessionQueue(sessionKey);
  const normalized = normalizeContextKey(contextKey);
  return normalized !== (existing?.lastContextKey ?? null);
}

export function enqueueSystemEventEntry(
  text: string,
  options: SystemEventOptions,
): SystemEvent | null {
  const event = enqueueOwnedSystemEventEntry(text, options);
  return event ? cloneSystemEvent(event) : null;
}

function enqueueOwnedSystemEventEntry(
  text: string,
  options: SystemEventOptions,
  receiptOptions?: ReceiptOptions & { throwOnFull?: boolean },
): SystemEvent | null {
  const key = requireSessionKey(options.sessionKey);
  if (readExecRequestOwners(options)?.some((owner) => owner.signal.aborted)) {
    return null;
  }
  const sessionStorePath =
    options.sessionStorePath === undefined
      ? getSystemEventStorePath(key)
      : options.sessionStorePath;
  if (!isSystemEventStoreCurrent(key, sessionStorePath)) {
    recordSystemEventStoreReplaced();
    return null;
  }
  const entry = getOrCreateSessionQueue(key);
  const cleaned = text.trim();
  if (!cleaned) {
    return null;
  }
  const normalizedContextKey = normalizeContextKey(options.contextKey);
  const normalizedDeliveryContext = normalizeDeliveryContext(options.deliveryContext);
  const matches = (event: SystemEvent) =>
    (event.contextKey ?? null) === normalizedContextKey &&
    areDeliveryContextsEqual(event.deliveryContext, normalizedDeliveryContext);
  if (options.replace) {
    if (normalizedContextKey === null) {
      throw new Error("replaced system events require a contextKey");
    }
    const matching = entry.queue.filter(matches);
    if (matching.length === 1 && matching[0]?.text === cleaned) {
      return null;
    }
  } else if (receiptOptions?.allowDuplicate !== true) {
    const duplicate = (event: SystemEvent | undefined) =>
      event !== undefined && event.text === cleaned && matches(event);
    if (
      normalizedContextKey === null ? duplicate(entry.queue.at(-1)) : entry.queue.some(duplicate)
    ) {
      return null;
    }
  }
  if (entry.queue.length >= MAX_EVENTS && !(options.replace && entry.queue.some(matches))) {
    const error = new SystemEventQueueFullError();
    log.warn(error.message, { sessionKey: key });
    if (receiptOptions?.throwOnFull) {
      throw error;
    }
    return null;
  }
  if (options.replace) {
    entry.queue = entry.queue.filter((event) => !matches(event));
  }
  if (normalizedContextKey !== null) {
    entry.lastContextKey = normalizedContextKey;
  }
  const event: SystemEvent = withExecRequestOwners(
    {
      id: generateSecureUuid(),
      text: cleaned,
      ts: Date.now(),
      ...(sessionStorePath === undefined ? {} : { sessionStorePath }),
      contextKey: normalizedContextKey,
      deliveryContext: normalizedDeliveryContext,
      ...(options.fromConversationTurn ? { fromConversationTurn: true as const } : {}),
    },
    readExecRequestOwners(options),
  );
  entry.queue.push(event);
  return event;
}

export function enqueueSystemEvent(text: string, options: SystemEventOptions) {
  return enqueueOwnedSystemEventEntry(text, options) !== null;
}

/** Enqueues one occurrence and returns one-use removal ownership for its UUID. */
export function enqueueSystemEventWithReceipt(
  text: string,
  options: SystemEventOptions,
  receiptOptions?: ReceiptOptions,
): (() => boolean) | null {
  const event = enqueueOwnedSystemEventEntry(text, options, {
    ...receiptOptions,
    throwOnFull: true,
  });
  if (!event) {
    return null;
  }
  const sessionKey = requireSessionKey(options.sessionKey);
  return () => consumeSelectedSystemEventEntries(sessionKey, [event]).length > 0;
}

export function drainSystemEventEntries(sessionKey: string): SystemEvent[] {
  return drainSystemEventsWith(sessionKey, cloneSystemEvent);
}

function drainSystemEventsWith<T>(sessionKey: string, project: (event: SystemEvent) => T): T[] {
  const key = requireSessionKey(sessionKey);
  const entry = getSessionQueue(key);
  if (!entry || entry.queue.length === 0) {
    return [];
  }
  const out = entry.queue.map(project);
  // Reentrant consumers may hold this array; clear it in place before removing the queue.
  entry.queue.length = 0;
  entry.lastContextKey = null;
  queues.delete(key);
  return out;
}

function areDeliveryContextsEqual(left?: DeliveryContext, right?: DeliveryContext): boolean {
  if (!left && !right) {
    return true;
  }
  if (!left || !right) {
    return false;
  }
  return channelRouteDedupeKey(left) === channelRouteDedupeKey(right);
}

function matchesConsumedSystemEvent(queued: SystemEvent, consumed: SystemEvent): boolean {
  if (consumed.id !== undefined) {
    // Queue-owned IDs govern modern consumption; only legacy ID-less snapshots use structure.
    return queued.id === consumed.id;
  }
  return (
    queued.text === consumed.text &&
    queued.ts === consumed.ts &&
    (queued.contextKey ?? null) === (consumed.contextKey ?? null) &&
    areDeliveryContextsEqual(queued.deliveryContext, consumed.deliveryContext)
  );
}

function resetQueueState(key: string, entry: SessionQueue) {
  if (entry.queue.length === 0) {
    entry.lastContextKey = null;
    queues.delete(key);
    return;
  }
  entry.lastContextKey =
    entry.queue.findLast((event) => event.contextKey != null)?.contextKey ?? null;
}

export function consumeSelectedSystemEventEntries(
  sessionKey: string,
  consumedEntries: readonly SystemEvent[],
  options?: { deferredEventIds?: readonly string[] },
): SystemEvent[] {
  const key = requireSessionKey(sessionKey);
  const entry = getSessionQueue(key);
  if (!entry || entry.queue.length === 0 || consumedEntries.length === 0) {
    return [];
  }
  // Prompt admission can defer captured occurrences to a delivery owner. Selection
  // still resolves against the live queue, in captured order, never late arrivals.
  const deferredIds = new Set(options?.deferredEventIds);
  const selected: SystemEvent[] = [];
  for (const consumed of consumedEntries) {
    const index = entry.queue.findIndex((event) => matchesConsumedSystemEvent(event, consumed));
    if (index === -1) {
      continue;
    }
    const event = entry.queue[index];
    if (event) {
      if (!event.id || !deferredIds.has(event.id)) {
        entry.queue.splice(index, 1);
      }
      selected.push(cloneSystemEvent(event));
    }
  }
  resetQueueState(key, entry);
  return selected;
}

export function drainSystemEvents(sessionKey: string): string[] {
  return drainSystemEventsWith(sessionKey, (event) => event.text);
}

export function peekSystemEventEntries(sessionKey: string): SystemEvent[] {
  return getSessionQueue(sessionKey)?.queue.map(cloneSystemEvent) ?? [];
}

/** Routed completions retain request ownership after process output expires. Stop is a cold path. */
export function peekExecRequestSystemEventEntries(
  target: ExecRequestIdentity,
): Array<{ sessionKey: string; events: SystemEvent[] }> {
  const selected = [];
  for (const sessionKey of queues.keys()) {
    const events = peekSystemEventEntries(sessionKey).filter((event) =>
      readExecRequestOwners(event)?.some((owner) => execRequestMatches(owner, target)),
    );
    if (events.length > 0) {
      selected.push({ sessionKey, events });
    }
  }
  return selected;
}

export function peekSystemEvents(sessionKey: string): string[] {
  return getSessionQueue(sessionKey)?.queue.map((event) => event.text) ?? [];
}

export function hasSystemEvents(sessionKey: string) {
  return (getSessionQueue(sessionKey)?.queue.length ?? 0) > 0;
}

export function resolveSystemEventDeliveryContext(
  events: readonly SystemEvent[],
): DeliveryContext | undefined {
  let resolved: DeliveryContext | undefined;
  for (const event of events) {
    resolved = mergeDeliveryContext(event.deliveryContext, resolved);
  }
  return resolved;
}

export function resetSystemEventsForTest() {
  queues.clear();
}

export function peekDeliverableSystemEventEntries(sessionKey: string): SystemEvent[] {
  return peekSystemEventEntries(sessionKey).filter((event) => !event.deliveryHeld);
}
export function holdSystemEventDelivery(
  sessionKey: string,
  attempted: readonly SystemEvent[],
): void {
  for (const event of getSessionQueue(sessionKey)?.queue ?? []) {
    if (attempted.some((candidate) => matchesConsumedSystemEvent(event, candidate))) {
      event.deliveryHeld = true;
    }
  }
}
