import type { PluginCompatRecord } from "./types.js";

const MARKING_DATE = "2026-07-25";
const DEPRECATION_MARKING = {
  status: "removal-pending",
  introduced: MARKING_DATE,
  deprecated: MARKING_DATE,
  warningStarts: MARKING_DATE,
  removeAfter: "2026-10-01",
} as const;

/** The elapsed window does not replace each family's required reader-migration proof. */
export const DEPRECATION_MARKING_COMPAT_RECORDS = [
  {
    code: "plugin-sdk-channel-setup-input-fields",
    ...DEPRECATION_MARKING,
    owner: "channel",
    replacement:
      "plugin-local setup input intersections that declare each owning channel field; retain each field until a new published-plugin artifact sweep finds no reader",
    docsPath: "/plugins/sdk-migration#published-channel-setup-compatibility",
    surfaces: [
      "ChannelSetupInput.privateKey",
      "ChannelSetupInput.secret",
      "ChannelSetupInput.botToken",
      "ChannelSetupInput.appToken",
      "ChannelSetupInput.signingSecret",
      "ChannelSetupInput.mode",
      "ChannelSetupInput.cliPath",
      "ChannelSetupInput.authDir",
      "ChannelSetupInput.httpUrl",
      "ChannelSetupInput.httpPort",
      "ChannelSetupInput.webhookPath",
      "ChannelSetupInput.webhookUrl",
      "ChannelSetupInput.userId",
      "ChannelSetupInput.accessToken",
      "ChannelSetupInput.password",
      "ChannelSetupInput.deviceName",
      "ChannelSetupInput.url",
      "ChannelSetupInput.baseUrl",
      "ChannelSetupInput.code",
      "ChannelSetupInput.groupChannels",
      "ChannelSetupInput.dmAllowlist",
      "ChannelSetupInput.autoDiscoverChannels",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on the reader-backed ChannelSetupInput compatibility tier",
      "published-plugin artifact reader sweep required before field removal",
    ],
    tests: ["src/plugin-sdk/channel-setup.test.ts", "src/plugins/compat/registry.test.ts"],
    releaseNote:
      "ChannelSetupInput keeps its reader-backed channel fields through the dated migration window while plugins move them into plugin-local input types.",
  },
  {
    code: "plugin-sdk-broad-runtime-barrels",
    ...DEPRECATION_MARKING,
    owner: "sdk",
    replacement:
      "focused plugin SDK subpaths for each runtime capability; retain until bundled and published plugins no longer import any of the seven broad barrels",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "openclaw/plugin-sdk/agent-runtime",
      "openclaw/plugin-sdk/agent-runtime loadModelCatalog params.useCache",
      "openclaw/plugin-sdk/agent-runtime loadModelCatalog params.cacheOnly",
      "openclaw/plugin-sdk/agent-runtime loadModelCatalog params.metadataSnapshot",
      "openclaw/plugin-sdk/agent-runtime loadModelCatalog",
      "openclaw/plugin-sdk/cli-runtime",
      "openclaw/plugin-sdk/conversation-runtime",
      "openclaw/plugin-sdk/hook-runtime",
      "openclaw/plugin-sdk/media-runtime",
      "openclaw/plugin-sdk/media-runtime buildAgentMediaPayload",
      "openclaw/plugin-sdk/plugin-runtime",
      "openclaw/plugin-sdk/security-runtime",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on broad plugin SDK barrels",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugins/contracts/plugin-sdk-subpaths.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Broad agent, CLI, conversation, hook, media, plugin, and security runtime barrels remain available while bundled and external plugins migrate to focused subpaths.",
  },
  {
    code: "plugin-sdk-provider-owned-helper-shims",
    ...DEPRECATION_MARKING,
    owner: "provider",
    replacement:
      "provider-local auth, model, replay, OAuth, and stream helper APIs; retain until every helper is migrated in official providers and absent from published plugins",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "openclaw/plugin-sdk/provider-stream MOONSHOT_THINKING_STREAM_HOOKS",
      "openclaw/plugin-sdk/provider-stream-shared defaultToolStreamExtraParams",
      "openclaw/plugin-sdk/provider-stream-shared stripTrailingAnthropicAssistantPrefillWhenThinking",
      "openclaw/plugin-sdk/provider-stream-shared createAnthropicThinkingPrefillPayloadWrapper",
      "openclaw/plugin-sdk/provider-stream-shared OpenAICompatibleThinkingLevel",
      "openclaw/plugin-sdk/provider-stream-shared isOpenAICompatibleThinkingEnabled",
      "openclaw/plugin-sdk/provider-stream-shared DeepSeekV4ThinkingLevel",
      "openclaw/plugin-sdk/provider-stream-shared DeepSeekV4ReasoningEffort",
      "openclaw/plugin-sdk/provider-stream-shared createDeepSeekV4OpenAICompatibleThinkingWrapper",
      "openclaw/plugin-sdk/provider-stream-shared createThinkingOnlyFinalTextWrapper",
      "openclaw/plugin-sdk/provider-stream-shared createGoogleThinkingPayloadWrapper",
      "openclaw/plugin-sdk/provider-stream-shared createGoogleThinkingStreamWrapper",
      "openclaw/plugin-sdk/provider-model-shared isProxyReasoningUnsupportedModelHint",
      "openclaw/plugin-sdk/provider-model-shared NATIVE_ANTHROPIC_REPLAY_HOOKS",
      "openclaw/plugin-sdk/provider-model-shared PASSTHROUGH_GEMINI_REPLAY_HOOKS",
      "openclaw/plugin-sdk/provider-auth toFormUrlEncoded",
      "openclaw/plugin-sdk/provider-auth generatePkceVerifierChallenge",
      "openclaw/plugin-sdk/provider-oauth-runtime OAuthProvider",
      "openclaw/plugin-sdk/provider-oauth-runtime OAuthProviderInfo",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations naming provider-local replacements",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugins/contracts/plugin-sdk-subpaths.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Provider-specific auth, model, replay, OAuth, and stream shortcuts remain as deprecated SDK shims while providers move to their local APIs.",
  },
  {
    code: "message-presentation-legacy-bridges",
    ...DEPRECATION_MARKING,
    owner: "channel",
    replacement:
      "MessagePresentation values and channel presentation renderers; retain until reply producers and official channel packages no longer emit or read legacy interactive replies",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "InteractiveReplyButton.value",
      "InteractiveReplyButton.url",
      "InteractiveReplyButton.webApp",
      "InteractiveReplyButton.web_app",
      "InteractiveReplyOption.value",
      "InteractiveReplyButton",
      "InteractiveReplyOption",
      "InteractiveReplyBlock",
      "InteractiveReply",
      "normalizeInteractiveReply",
      "hasInteractiveReplyBlocks",
      "presentationToInteractiveReply",
      "presentationToInteractiveControlsReply",
      "interactiveReplyToPresentation",
      "resolveInteractiveTextFallback",
      "src/auto-reply ReplyPayload.interactive",
      "openclaw/plugin-sdk/reply-payload ReplyPayload.interactive",
      "reduceInteractiveReply",
      "@openclaw/discord buildDiscordInteractiveComponents",
      "@openclaw/slack buildSlackInteractiveBlocks",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations naming MessagePresentation replacements",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/interactive/payload.test.ts",
      "src/plugin-sdk/reply-payload.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Legacy interactive reply values and channel-specific rendering bridges remain available while producers migrate to MessagePresentation.",
  },
  {
    code: "plugin-sdk-focused-compat-aliases",
    ...DEPRECATION_MARKING,
    owner: "sdk",
    replacement:
      "the focused replacement named by each TypeScript @deprecated annotation; retain until every enumerated alias has zero bundled and published readers",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "openclaw/plugin-sdk/acp-runtime __testing",
      "openclaw/plugin-sdk/channel-inbound BuildChannelTurnContextParams",
      "openclaw/plugin-sdk/channel-inbound BuiltChannelTurnContext",
      "openclaw/plugin-sdk/channel-inbound buildChannelTurnContext",
      "openclaw/plugin-sdk/channel-inbound finalizeChannelInboundContext",
      "openclaw/plugin-sdk/channel-inbound filterChannelTurnSupplementalContext",
      "openclaw/plugin-sdk/channel-send-result ChannelSendRawResult",
      "openclaw/plugin-sdk/keyed-async-queue KeyedAsyncQueue.getTailMapForTesting",
      "openclaw/plugin-sdk/persistent-dedupe PersistentDedupeLegacyPathOptions.lockOptions",
      "openclaw/plugin-sdk/retry-runtime createTelegramRetryRunner",
      "openclaw/plugin-sdk/ssrf-policy SsrfPolicyOptions.allowPrivateNetwork",
      "openclaw/plugin-sdk/ssrf-policy ssrfPolicyFromAllowPrivateNetwork",
      "openclaw/plugin-sdk/tts-runtime TtsSynthesisStreamResult",
      "openclaw/plugin-sdk/tts-runtime TtsRuntimeFacade._test",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations naming focused replacements",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugin-sdk/channel-inbound.test.ts",
      "src/plugin-sdk/ssrf-policy.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Focused SDK compatibility aliases remain available through a dated window while callers adopt their annotated replacements.",
  },
  {
    code: "agent-harness-terminal-result-aliases",
    ...DEPRECATION_MARKING,
    owner: "agent-runtime",
    replacement:
      "AgentHarnessAttemptResult.terminal and AgentHarnessDeliveryDefaults.visibleReplies; retain until harness migration verifies that legacy terminal fields and sourceVisibleReplies are unread",
    docsPath: "/plugins/sdk-agent-harness",
    surfaces: [
      "AgentHarnessAttemptResult.aborted",
      "AgentHarnessAttemptResult.externalAbort",
      "AgentHarnessAttemptResult.timedOut",
      "AgentHarnessAttemptResult.idleTimedOut",
      "AgentHarnessAttemptResult.timedOutDuringCompaction",
      "AgentHarnessAttemptResult.timedOutDuringToolExecution",
      "AgentHarnessAttemptResult.timedOutByRunBudget",
      "AgentHarnessAttemptResult.promptError",
      "AgentHarnessAttemptResult.promptErrorSource",
      "AgentHarnessDeliveryDefaults.sourceVisibleReplies",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on agent harness result and delivery defaults",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/agents/harness/settled-turn-finalization-result.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Agent harness result booleans and sourceVisibleReplies remain available while harnesses migrate to terminal outcomes and visibleReplies.",
  },
  {
    code: "official-plugin-export-aliases",
    ...DEPRECATION_MARKING,
    owner: "channel",
    replacement:
      "MessagePresentation renderers and host-owned timeout/runtime behavior; retain until minimum supported official plugin packages no longer import these aliases",
    docsPath: "/plugins/compatibility#current-compatibility-areas",
    surfaces: [
      "@openclaw/discord buildDiscordInteractiveComponents",
      "@openclaw/discord normalizeDiscordListenerTimeoutMs",
      "@openclaw/discord normalizeDiscordInboundWorkerTimeoutMs",
      "@openclaw/discord isAbortError",
      "@openclaw/discord runDiscordTaskWithTimeout",
      "@openclaw/slack buildSlackInteractiveBlocks",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on published official-plugin exports",
      "plugin boundary report compatibility inventory",
    ],
    tests: ["src/plugins/compat/registry.test.ts"],
    releaseNote:
      "Published channel presentation and Discord timeout aliases remain available while consumers move to their canonical exports and host-owned behavior.",
  },
  {
    code: "memory-host-compatibility-aliases",
    ...DEPRECATION_MARKING,
    owner: "sdk",
    replacement:
      "canonical memory cache/FTS tables; retain until supported memory integrations are verified to use canonical tables without overrides and legacy table data remains preserved",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "@openclaw/memory-host-sdk ensureMemoryIndexSchema.embeddingCacheTable",
      "@openclaw/memory-host-sdk ensureMemoryIndexSchema.ftsTable",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on memory-host SDK compatibility fields",
      "plugin boundary report memory-host SDK summary",
    ],
    tests: [
      "packages/memory-host-sdk/src/host/memory-schema.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Memory-host table overrides remain available until supported artifact usage and legacy data preservation are verified.",
  },
  {
    code: "plugin-runtime-api-compat-aliases",
    ...DEPRECATION_MARKING,
    owner: "plugin-execution",
    replacement:
      "the namespaced plugin API and focused runtime methods named per surface; retain until all enumerated flat API and runtime aliases have no readers",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "OpenClawPluginApi.registerSessionExtension",
      "OpenClawPluginApi.enqueueNextTurnInjection",
      "OpenClawPluginApi.registerControlUiDescriptor",
      "OpenClawPluginApi.registerRuntimeLifecycle",
      "OpenClawPluginApi.registerAgentEventSubscription",
      "OpenClawPluginApi.emitAgentEvent",
      "OpenClawPluginApi.setRunContext",
      "OpenClawPluginApi.getRunContext",
      "OpenClawPluginApi.clearRunContext",
      "OpenClawPluginApi.registerSessionSchedulerJob",
      "OpenClawPluginApi.registerSessionAction",
      "OpenClawPluginApi.sendSessionAttachment",
      "OpenClawPluginApi.scheduleSessionTurn",
      "OpenClawPluginApi.unscheduleSessionTurnsByTag",
      "PluginHookContext.senderExternalId",
      "PluginAttachmentChannelHints.telegram",
      "PluginAttachmentChannelHints.slack",
      "AgentPromptSurfaceKind pi_main",
      "PluginRuntime.channel.reply.createReplyDispatcherWithTyping",
      "PluginRuntime.channel.reply.resolveHumanDelayConfig",
      "PluginRuntime.channel.reply.dispatchReplyFromConfig",
      "PluginRuntime.channel.reply.finalizeInboundContext",
      "PluginRuntime.channel.media.fetchRemoteMedia",
      "PluginRuntime.channel.session.resolveStorePath",
      "PluginRuntime.channel.session.recordInboundSession",
      "PluginRuntime.channel.inbound.runPreparedReply",
      "PluginRuntime.channel.turn",
      "PluginRuntime.system.requestHeartbeatNow",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on plugin API and runtime aliases",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugins/captured-registration.test.ts",
      "src/plugins/runtime/index.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Flat plugin registration and broad runtime aliases remain available while plugins migrate to namespaced APIs and focused runtime methods.",
  },
  {
    code: "plugin-provider-manifest-compat-aliases",
    ...DEPRECATION_MARKING,
    owner: "provider",
    replacement:
      "manifest-owned plugin kind/setup metadata and model catalog registration; retain until providers no longer publish runtime kind or legacy catalog hooks",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "DefinePluginEntryOptions.kind",
      "SingleProviderPluginOptions.kind",
      "OpenClawPluginDefinition.kind",
      "PluginPackageChannel.cliAddOptions",
      "ProviderPlugin.catalog",
      "ProviderPlugin.staticCatalog",
      "ProviderPlugin.suppressBuiltInModel",
      "ProviderPlugin.augmentModelCatalog",
      "ProviderBuiltInModelSuppressionContext",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on plugin manifest and provider catalog aliases",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugins/contracts/package-manifest.contract.test.ts",
      "src/plugins/contracts/provider-catalog-deprecation.contract.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Runtime plugin kind/setup metadata and provider catalog hooks remain available while plugins migrate ownership into manifests and catalog registrations.",
  },
] as const satisfies readonly PluginCompatRecord[];
